ita-social-projects/horondi_client_fe

src/pages/cart/filled-cart/filled-cart.js
src/pages/cart/filled-cart/filled-cart.styles.js
src/translations/cart.translations.js

deleted no need buttons and replace it to back button at the top

Cart fixes v.2

---

src/pages/error-page/error-page.js
src/translations/errorpage.translations.js

fixed the display of various error messages on the error page

Fix error page messages

---

public/index.html

fix fb messenger

---

cypress/integration/order-history.test.js

finished e2e test for empty order history page

finished e2e tests for order history page

---

src/redux/user/user.sagas.js

it's needed for Google Logination

in user.sagas id_token->idToken

---

public/index.html
src/configs/index.js
src/pages/login/login.js
src/translations/user.translations.js

-fixed user registration
-removed integrity from index.html
-added messages when user tries to login with empty input fields

fixed user registration & added message for required fields

---

.github/workflows/main.yml
Dockerfile
azure-pipelines.yml

Lock NodeJS version for build container of CD

Lock nodejs version

---

src/pages/product-list-page/product-list-filter/product-list-filter.js

fix styling

---

src/pages/product-list-page/product-list-filter/product-list-filter.js

fix handle filter clear

---

src/configs/routes.js
src/containers/checkout/checkout-form/checkout-form.js
src/containers/checkout/checkout-form/checkout-form.styles.js
src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.styles.js
src/containers/checkout/checkout.js
src/pages/thanks-page/order-data/index.js
src/pages/thanks-page/order-data/order-data.js
src/pages/thanks-page/order-data/order-data.styles.js
src/pages/thanks-page/order-data/order-item-card/index.js
src/pages/thanks-page/order-data/order-item-card/order-item-card.js
src/pages/thanks-page/order-data/order-item-card/order-item-card.styles.js
src/pages/thanks-page/thanks-page.js
src/pages/thanks-page/thanks-page.styles.js
src/redux/cart/cart.sagas.js
src/redux/order/order.actions.js
src/redux/order/order.operations.js
src/redux/order/order.sagas.js
src/redux/order/order.types.js
src/services/local-storage.service.js
src/translations/thanks-page.translations.js
src/utils/order.js
src/utils/thank-you.js

implement "thank you  for order" page

---

.github/pull_request_template.md

add checkbox for linking issue

add checkbox for linking issue

---

src/pages/home/our-looks/our-looks.js

fix image reflection

---

src/redux/images-constructor/constructor-basic/tests/constructor-basic.actions.test.js
src/redux/images-constructor/constructor-basic/tests/constructor-basic.reducer.test.js
src/redux/images-constructor/constructor-basic/tests/constructor-basic.sagas.test.js
src/redux/images-constructor/constructor-bottom/tests/constructor-bottom.actions.test.js
src/redux/images-constructor/constructor-bottom/tests/constructor-bottom.reducer.test.js
src/redux/images-constructor/constructor-bottom/tests/constructor-bottom.sagas.test.js
src/redux/images-constructor/constructor-front-pocket/tests/constructor-front-pocket.actions.test.js
src/redux/images-constructor/constructor-front-pocket/tests/constructor-front-pocket.reducer.test.js
src/redux/images-constructor/constructor-front-pocket/tests/constructor-front-pocket.sagas.test.js
src/redux/images-constructor/constructor-model/tests/constructor-model.actions.test.js
src/redux/images-constructor/constructor-model/tests/constructor-model.reducer.test.js
src/redux/images-constructor/constructor-model/tests/constructor-model.sagas.test.js
src/redux/images-constructor/constructor-pattern/tests/constructor-pattern.actions.test.js
src/redux/images-constructor/constructor-pattern/tests/constructor-pattern.reducer.test.js
src/redux/images-constructor/constructor-pattern/tests/constructor-pattern.sagas.test.js
src/redux/images-constructor/constructor.variables.js

Create action, reducer and saga tests for each of:  
constructor basic
constructor-bottom
constructor front-pocket
constructor model
constructor pattern
tests for constructor basic:
tests for constructor bottom:
tests for constructor front-pocket:
tests for constructor model:
tests for constructor pattern:

constructor redux tests/583

---

src/pages/images-constructor/hooks.js
src/pages/images-constructor/images-constructor.js

When we change the constructor image our image jump

fix constructor image jump

---

package-lock.json
package.json
src/pages/images-constructor/images-constructor.js

https://www.npmjs.com/package/horondi_merge_images
https://github.com/ita-social-projects/horondi_merge_images

added mergeImages module

---

src/redux/order/order.sagas.js

Fix Fondy error #632

---

src/containers/header-profile/header-profile.js

Fixed jumping drop down menu
Before logout
After logout

Fix jumping drop down menu

---

src/redux/news/tests/news.saga.test.js
src/redux/order/order.sagas.js
src/redux/order/tests/order.actions.test.js
src/redux/order/tests/order.reducer.test.js
src/redux/order/tests/order.sagas.test.js
src/redux/order/tests/order.variables.js

writing unit test for redux orders #582

---

src/pages/materials/materials.js
src/pages/materials/materials.style.js
src/pages/materials/slider/index.js
src/pages/materials/slider/slider.js
src/pages/materials/slider/slider.styles.js
src/redux/pattern/pattern.operations.js

Fixed a bug
Refactored slider accordingly to mock-up

Fix and refactor "Material page" #610

---

src/configs/index.js
src/const/checkout.js
src/containers/checkout/checkout-form/checkout-form.js
src/containers/checkout/checkout-form/delivery/delivery.js
src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.js
src/containers/orders/order/delivery-type/delivery-type.js
src/index.js
src/services/session-storage.service.js
src/utils/checkout.js

Inputs field on checkout form are field by user's data if user is authorized
Also all field data now are saved when you moved to another page and back to the checkout

Save filled data on checkout and fill checkout with authorized user's data

---

src/configs/index.js
src/containers/header-profile/header-profile.js
src/pages/new-password/new-password.js
src/pages/register/register.js
src/pages/register/register.styles.js
src/redux/cart/cart.operations.js
src/redux/user/user.sagas.js
src/translations/user.translations.js

Added storing return path in session storage so the user will be returned to the same page after registration and press on the button "Continue shopping".

Return User to the same page where they were after registration

---

.gitignore
src/components/dropdown/dropdown.js
src/containers/chat/active-messenger/active-messenger.js
src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
src/containers/search-bar-list/search-bar-list.js
src/pages/confirmation/confirmation.js
src/pages/login/login.js
src/pages/new-password/new-password.js
src/pages/product-details/comments/comments.js
src/pages/product-list-page/product-list-item/product-list-item.js
src/pages/profile-page/profile-page.js
src/pages/recovery/recovery.js
src/pages/register/register-from/index.js
src/pages/register/register-from/register-form.js
src/pages/register/register-from/register-form.styles.js
src/pages/register/register.js
src/pages/register/register.styles.js
src/serviceWorker.js
src/utils/handle-active-massenger.js
src/utils/handle-comments.js
src/utils/handle-confirmation.js
src/utils/handle-login.js
src/utils/handle-new-password.js
src/utils/handle-product-list-item.js
src/utils/handle-profile-page.js
src/utils/handle-recovery-page.js
src/utils/handle-search-bar-list.js

Fix sonar code smells
- moved nested ternary operators into separate functions and files (utils directory)
- refactor functions for Cognitive Complexity (create separate functions and files)

Fix sonar codesmells #555

---

src/redux/user/user.sagas.js
src/utils/client.js

hotfix. Response errors handling

---

src/pages/product-details/product-details.js

Default size(small PR)

---

src/containers/orders/cart/cart-item/cart-item.js
src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
src/pages/wishlist/wishlist-item/wishlist-item.js

fixed undefined routes

---

src/redux/model/model.operations.js

hotfix towards front page with bad fetching of models

fixed pagination

---

src/redux/user/tests/user.actions.test.js
src/redux/user/tests/user.mocks.js
src/redux/user/tests/user.reducer.test.js
src/redux/user/tests/user.sagas.test.js

Improved coverage for user actions/reducer and added tests for user sagas.
Closes #744 
user actions
user reducer
user sagas

Tests for user actions/reducer/sagas #744

---

src/pages/product-list-page/count-per-page/count-per-page.js
src/pages/product-list-page/product-list-page.js

So, the eslint errors was coused through "==" but expected "===" in 2 files. In this 2 files I check the types of comparable values an it were different, one was the string and another a number, in both cases. Thats why I convert string to number by Number(). Then I cange "==" to "===" and now it compare correctly. 
Also I check In localhost where this changes take place, one is in CountPerPage component, and another is paginationCondition. All is working correctly, as before my changes.
** original screenshot ** 
|  ** updated screenshot **

(SP:2)Fix eslint errors #779

---

README.md

added git repo and photo new team member

added git repo and photo new team member

---

src/pages/contacts/contacts.styles.js

fixed styles on contact page

---

.eslintrc

I have fixed semi rules in .eslintrc file.
I have added semi and semi-style rules.
It will allow us to prevent errors in code 
with using semicolons.
- [ yes] 🔽 My branch is up-to-date with "development" branch
- [ yes] ✅All tests passed locally
- [ https://github.com/ita-social-projects/horondi_client_fe/issues/758] 🔗 Link pull request to issue

fixed semi rule

---

.github/workflows/main.yml
src/containers/currency/currency.js
src/pages/business-page/business-page.js

Created the eslint checking step in CI

added new step

---

src/pages/home/slider/slider-home-page.js
src/redux/homepage-slider/homepage-slider.operations.js

fixed slider to sync its work with the changes I made on admin part of the project

fixed frontend slider

---

README.md

upload photo and git repo

---

src/components/google-log-in-btn/google-button.js
src/redux/user/user.operations.js

fixed google authentication

---

README.md

Update README.md | Adding photos to front

Update README.md | Adding photos to front

---

src/containers/checkout/checkout-form/checkout-form.js
src/redux/order/order.operations.js
src/redux/order/order.sagas.js

Hot fix bug in orders

---

src/pages/news/news-page/news-page.style.js

Remove @media to fix responsive design < 768px

Fix responsive design of "News" page #838

---

public/index.html

generated and added integrity

---

src/pages/contacts/contacts.js

In schedule section were unnecessary <span> element which was the reason of responsive design bug described in issue.
** ![image](https://user-images.githubusercontent.com/39667486/128600126-176a4ffd-8a8e-4dc1-bc33-59d153aed617.png) **  |  ** ![image](https://user-images.githubusercontent.com/39667486/128600157-5bf15999-94a9-4afd-a9a5-adbd6a3080e5.png) **

Fixing schedule field bug

---

src/components/number-input/number-input.js
src/pages/cart/cart.js

Fixed cart loading when adding item to cart while logged in, and restricted max quantity to 1000

Fix loading when you use some order #804

---

src/containers/footer-links/footer-links.js
src/containers/header-profile/header-profile.js
src/containers/sidebar/sidebar.js
src/containers/sidemenu-right-bar/sidemenu-right-bar.js
src/pages/news/news-page/news-page.js

Fix isMenuOpen & slider in news-page

Fix isMenuOpen & slider in news-page

---

src/redux/user/tests/user.sagas.test.js
src/redux/user/user.sagas.js

Login test

---

src/redux/user/tests/user.sagas.test.js
src/redux/user/user.sagas.js

uncommented return

---

Dockerfile

ssh access

---

src/components/app-header/app-header.js
src/containers/header-right-bar/header-right-bar.js

Throw function setIsMenuOpen through HeaderRightBar to HeaderProfile

Add function setIsMenuOpen as a prop through HeaderRightBar

---

Dockerfile

reverted expose change

---

Dockerfile

added lock-file to dockerfile when we build a project

added lock-file to dockerfile

---

src/components/app-footer/app-footer.styles.js

Fixed footer responsive design bug on display 552-770px

Fixed footer responsive design bug

---

src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/order/order-table/order-table.js

Added modal showing when we try to remove item from cart.

added modal to cart

---

src/containers/chat/chat.style.js

Fixed bug with position of "Contact us" block for monitors with different heights. Also changed responsive design width value for displays with max-width 768px.

Fixed bug with position of "Contact us" block

---

src/utils/checkout.js

Update orders method after order migration in frontend

Update orders method after order migration in frontend

---

src/pages/home/categories-list/categories-list.js

Now products on homepage with correct links

fixed urls on homepage

---

src/redux/order/order.sagas.js

Removed "* 100"
The program crashed due to too large values

removed *100 from orders amount

---

src/index.css

added padding = 0 to the body tag

Fix scrollbar displaying when menu open

---

src/configs/index.js
src/pages/login/login.js
src/redux/user/tests/user.mocks.js
src/redux/user/tests/user.sagas.test.js
src/translations/user.translations.js
src/validators/login.js

You should launch this code with this PR from BackEnd - https://github.com/ita-social-projects/horondi_client_be/pull/799
I fixed color displaying of "Stay signed in" button.
Also I renamed it to "Remember me".

fixed checkbox colors and renamed it from StaySignedIn to RememberMe

---

src/redux/user/tests/user.sagas.test.js
src/redux/user/user.operations.js
src/redux/user/user.sagas.js

Closes#844 Fixed wishlist for google users

fixed wishlist for google users

---

src/pages/login/login.js
src/pages/login/login.styles.js

Changed 'forgot password?' position.
Also cleaned some css styles on Login page.

Changed 'forgot password?' position #868

---

src/pages/login/login.js
src/pages/login/login.styles.js
src/translations/user.translations.js
src/validators/login.js

fixed bug when Error message below 'Email' field does not appear
I changed Formik using method so now onBlur validation should work correctly
Before:
After:

fixed bug when Error message below 'Email' field does not appear

---

src/translations/cart.translations.js

fixed [Your Cart-Checkout page] translation in English 'Nova post' delivery is not correct

[Your Cart-Checkout page] translation in English 'Nova post' delivery is not correct

---

src/pages/login/tests/login-page.test.js

create tests for login page

---

src/translations/cart.translations.js

Fixed bug with Delivery type names translation #762

fixed bug with Delivery type names translation

---

src/pages/register/tests/mockStore.js
src/pages/register/tests/register.test.js

tests/911 Created test for register

---

src/containers/checkout/checkout-form/checkout-form.js
src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/order-history/order-history-order-item/order-history-order-item.js
src/containers/orders/order-history/order-history-order/order-history-order.js
src/containers/orders/order/delivery-type/delivery-type.js
src/pages/product-details/product-details.js
src/pages/product-details/product-info/product-info.js
src/pages/product-details/product-sizes/product-sizes.js
src/pages/product-details/product-submit/product-submit.js
src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
src/pages/product-details/similar-products/similar-products.js
src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
src/pages/product-list-page/product-list-item/product-list-item.js
src/pages/wishlist/wishlist-item/wishlist-item.js
src/redux/cart/cart.operations.js
src/redux/cart/cart.sagas.js
src/redux/order/order.sagas.js
src/redux/products/products.operations.js
src/redux/user/user.operations.js
src/translations/order.translations.js
src/translations/product-list.translations.js
src/utils/checkout.js
src/utils/price.js
src/utils/priceCalculating.js

Linked to - https://github.com/ita-social-projects/horondi_client_be/pull/840
Refactored catalog product prices
Refactored cart product prices
Refactored order by cash product prices
Refactored wishlist product prices
Refactored orderhistory product prices
Refactored order by card product prices
Edited tests

fixed price displaying in cart, wishlist, orders and catalog

---

src/containers/cart-header/cart-header.js
src/containers/cart-header/cart-header.styles.js
src/containers/currency/currency.styles.js
src/containers/header-profile/header-profile.styles.js
src/containers/header-right-bar/header-right-bar.js
src/containers/header-right-bar/header-right-bar.styles.js
src/containers/language/language.styles.js

fix buttons styles

---

src/containers/currency/currency-component.js
src/containers/currency/currency.js
src/containers/currency/index.js
src/containers/header-right-bar/header-right-bar.js

add hook for currency

---

src/configs/index.js

fixed snackbar message

---

.eslintrc
src/containers/footer-lists/tests/footer-lists.test.js
src/pages/home/categories-list/tests/categories-list.test.js
src/serviceWorker.js

added new rule to esling: "no-console: 'error'"

changed no-console rule

---

README.md

Add 12 team to readme

---

src/locales/en/product-list-page.json
src/locales/ua/product-list-page.json
src/pages/product-list-page/product-list-page.js

Delete unusable variable from translation file and fix showFilterButton
- [https://github.com/ita-social-projects/horondi_client_fe/issues/1062 ] 🔗 Link pull request to issue

fix bug and delete unusable variable

---

src/configs/index.js
src/pages/contacts/contacts.js
src/redux/contacts/contacts.operations.js

Fixed map displaying in contact for new back-end part
| ** ![Screenshot_32](https://user-images.githubusercontent.com/67831961/137595598-a1a89fc3-c666-4a4d-a521-effe2c233e06.png) ** | ** ![Screenshot_33](https://user-images.githubusercontent.com/67831961/137595602-9386b292-e538-4633-8d4c-6631a2a27339.png) ** |

fixed map displaying for new back-end part

---

.gitignore

added .env.example to .gitignore

add .env.example to .gitignore

---

src/pages/home/models-list/tests/models-list.spec.js

Refactor models-list test. Delete all trash

refactoring/1109/models-list . refactor test. Delete all trash

---

src/pages/product-details/comments/comments-item/reply-comments-item/tests/reply-comments-item.test.js

Fix tests failing

---

src/containers/checkout/checkout-form/checkout-form.js
src/containers/checkout/checkout-form/const.js
src/locales/en/checkout.json
src/locales/ua/checkout.json
src/utils/checkout.js

Fixed bug with payment translation.

bug fix in checkout

---

src/pages/not-found-page/not-found-page.js
src/pages/not-found-page/tests/__snapshots__/not-found-page.test.js.snap

fix error img

---

src/redux/toast/toast.sagas.js

fixed toast saga

---

src/pages/business-page/business-page.js
src/pages/business-page/operations/business-page.queries.js
src/tests/unit/pages/business-page/business-page.spec.js
src/tests/unit/pages/business-page/business-page.variables.js

Add translation to back-end part of data.
Back-end - https://github.com/ita-social-projects/horondi_client_be/pull/919

add translation to back-end part of data

---

src/containers/orders/order-history/order-history-order/order-history-order.js
src/containers/snackbar/snackbar.js
src/pages/order-history/operations/order-history.queries.js

Cleaned console errors in snackbar.js and order-history-order.js 
ORIGINAL:
UPDATED:

bugfix/1200/fixed console-errors in given components

---

src/pages/login/login.js
src/validators/login.js

Fixed translayion bug
|![image](https://user-images.githubusercontent.com/50678261/140486091-bd30232b-938f-40f4-805e-1b82fad2be82.png)|![image](https://user-images.githubusercontent.com/50678261/140486144-90f4e6fc-b820-4bae-bec8-38b368dd9445.png)|

Login translation bug

---

src/pages/business-page/business-page.js
src/pages/business-page/operations/business-page.queries.js
src/tests/unit/pages/business-page/business-page.spec.js
src/tests/unit/pages/business-page/business-page.variables.js

Fixed translation key in bussiness page without snake case.
Back-end - https://github.com/ita-social-projects/horondi_client_be/pull/935

Fixed translations key for bussiness pages

---

src/pages/home/operations/slider/slider.queries.js
src/pages/home/slider/slider-home-page.js

Added new approach for translation
Back-End - https://github.com/ita-social-projects/horondi_client_be/pull/929

1195/Header and homepage-slider translation refactor

---

src/hooks/use-translations-load.js

Fix translations

---

src/containers/checkout/checkout-form/delivery/courier/courier.js
src/containers/checkout/checkout-form/delivery/courier/courier.styles.js
src/locales/en/checkout.json
src/locales/ua/checkout.json
src/utils/checkout.js
src/validators/chekout.js

Added field for Courier Delivery Type (region and district). #1153 
Linked to (be part): https://github.com/ita-social-projects/horondi_client_be/pull/933

added fields for courier

---

src/hooks/use-translations-load.js

Reverts ita-social-projects/horondi_client_fe#1211

Revert "Fix translations"

---

src/pages/materials/materials.js
src/pages/materials/operations/getAllPatterns.queries.js

Fixed translations-key with camelCase.
Beck-end - https://github.com/ita-social-projects/horondi_client_be/pull/938

Fixed translation-key

---

src/pages/home/models-list/operations/getAllModels.queries.js

Added translationsKey to gql

---

src/pages/contacts/contacts.js
src/pages/contacts/operations/contacts.queries.js
src/tests/unit/pages/contacts/contacts.variables.js

https://github.com/ita-social-projects/horondi_client_be/pull/939

Fix naming

---

src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.js

Fixed in checkout ukr-post validationSchema on Front, when we click on change language button the language of validationSchema error change. The language change correctly

fixed checkout ukrposhta delivery address translate

---

src/containers/sidebar/sidebar-item/sidebar-item.js

- Codesmells was successfuly fixed

Codesmells was fixed

---

src/containers/chat/active-messenger/active-messenger.js
src/containers/chat/chat.js
src/containers/chat/chat.style.js
src/containers/chat/mail-form/mail-form.js

Removed ThemeContext from the Chat component

Removed ThemeContext from the Chat component

---

src/containers/checkout/checkout-form/checkout-form.js
src/containers/checkout/checkout.js

Removed ThemeContext from checkout

Removed ThemeContext from checkout

---

src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/cart/cart-item/cart-item.styles.js
src/containers/orders/cart/filled-cart/filled-cart.js
src/containers/orders/cart/filled-cart/filled-cart.styles.js
src/containers/orders/cart/path-back/path-back.js
src/containers/orders/cart/path-back/path-back.styles.js
src/containers/orders/order/order-table/order-table.js
src/containers/orders/order/order-table/order-table.styles.js

Removed ThemeContext from Cart

Removed ThemeContext from Cart

---

src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.js
src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.styles.js
src/containers/checkout/checkout-form/delivery/self-pickup/tests/self-pickup.spec.js
src/containers/checkout/checkout-form/tests/__snapshots__/checkout-form.spec.js.snap
src/containers/orders/order/order-table/order-table.js
src/containers/orders/order/order-table/tests/__snapshots__/order-table.test.js.snap

Fixed 5 console warnings on Cart and Checkout #1237

console warnings cart checkout

---

src/configs/index.js
src/locales/en/error.json
src/locales/ua/profilePage.json
src/pages/profile-page/profile-page.js
src/redux/user/user.operations.js

Fixed errors on profile page

---

src/components/app/app-theme/theme.js

Redesigned 404 page
| ![image](https://user-images.githubusercontent.com/57355852/141751075-09e03963-f0c8-4729-b65d-7ddf3cce0cdd.png)|![image](https://user-images.githubusercontent.com/57355852/141751319-0d0299e1-2b55-4aeb-ad73-e25ceb660d25.png)|
|![image](https://user-images.githubusercontent.com/57355852/141751701-87f60000-8b25-4445-a3aa-f10c2f02e5e2.png)|![image](https://user-images.githubusercontent.com/57355852/141751447-bc6858e9-6be6-4830-84b3-ecd238d488b2.png) |

Redesigned 404 page

---

src/containers/orders/order/order-table/order-table.js
src/pages/product-list-page/product-sort/product-sort.js

|         Original          |
| ![productSort_defaultValue](https://user-images.githubusercontent.com/61072426/141938408-afc0aeb2-0dc4-4033-b1d1-ad9ba45e3117.jpg) |
| ![yourCart_keyProp](https://user-images.githubusercontent.com/61072426/141938545-c41cbf11-dd28-4387-9aee-9cb1c2e46ab1.jpg) |
https://github.com/ita-social-projects/horondi_client_fe/issues/1290

bugfix/1290/fix console-warns in order-table.js and product-sort.js

---

src/containers/checkout/checkout-form/tests/__snapshots__/checkout-form.spec.js.snap
src/pages/thanks-page/order-data/order-data.js
src/pages/thanks-page/order-data/order-data.styles.js
src/pages/thanks-page/thanks-page.js
src/pages/thanks-page/thanks-page.styles.js

Removed ThemeContext from thanks page

Removed ThemeContext from thanks page

---

src/containers/checkout/checkout-form/tests/__snapshots__/checkout-form.spec.js.snap
src/pages/materials/materials.js
src/pages/materials/tests/materials.spec.js

Removed ThemeContext from materials

Removed ThemeContext from materials

---

src/containers/chat/active-messenger/active-messenger.js
src/containers/chat/active-messenger/tests/active-messenger.spec.js
src/serviceWorker.js

Fixed codesmels in serviceWorker and active-messenger tests

codsmels in serviceWorker and active messenger tests

---

src/containers/orders/cart/filled-cart/filled-cart.styles.js

Redesign CartPage
| ![image](https://user-images.githubusercontent.com/64384450/142464078-eff35f91-384c-4bfc-a84b-80eb774e735f.png) | ![image](https://user-images.githubusercontent.com/64384450/142463929-b923997c-ac95-48c8-8e3c-a2362be915f3.png)
|

change size ADD button

---

src/hooks/use-translations-load.js
src/utils/client.js

Fix feature when from local we were getting translations from staging

Change env

---

src/containers/sidebar/sidebar-item/sidebar-item.js

Cleaned console warning in side-bar
| ![Screenshot_1](https://user-images.githubusercontent.com/67831961/142881074-753210f2-d0fb-4a03-9489-d7d97f04a033.png) | ** updated screenshot ** |

Cleaned console warning in sidebar

---

src/i18n.js

Fixed translations
| ![Screenshot_3](https://user-images.githubusercontent.com/67831961/142924150-d692c85e-f85d-4e78-9154-617c6c352ae8.png) | ![Screenshot_4](https://user-images.githubusercontent.com/67831961/142924165-95fff041-62e1-43e0-953f-403c44349256.png) |

Fixed translations

---

src/pages/news/news-item/news-item.js

Cleaned console errors in news page

fixed propTypes

---

src/i18n.js

Fix transaltions

---

src/components/dropdown/dropdown.js
src/containers/sidebar/sidebar.js

Clean console errors in Sidebar and Dropdown components

clean console errors

---

src/components/modal/modal.js
src/components/modal/modal.styles.js
src/components/modal/tests/modal.spec.js
src/containers/orders/order/empty-order/empty-order.styles.js
src/images/modal-icon/modalCloseIcon.svg
src/index.css
src/locales/en/common.json
src/locales/en/modal.json
src/locales/ua/common.json
src/locales/ua/modal.json
src/pages/wishlist/filled-wishlist/filled-wishlist.js
src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
src/pages/wishlist/wishlist-item/wishlist-item.js
src/pages/wishlist/wishlist-item/wishlist-item.styles.js

Redesign wishlist page according to the new design on FE 
Cleare error in console
Create tests for Modal component

wishlist redesign

---

src/containers/products-filters-container/products-filters-container.js
src/pages/login/login.js

Clean console warnings in login and filter

Clean console warnings in login and filter 

---

public/index.html

Cleaned console warning about 'integrity'

Cleaned console warning about 'integrity'

---

src/redux/user/tests/user.sagas.spec.js
src/redux/user/user.sagas.js

Fixed routes after google logination from profile to last visited page.

Fixed routes in login

---

src/hooks/useIsLoadingOrError.js

Fixed console warnings in useIsLoadingOrError hook

Hotfix/1409/console warnings in useIsLoadingOrError hook

---

src/pages/home/slider/slider-home-page.js
src/pages/home/slider/slider-home-page.style.js

Fix position of arrows and button in slider on Homepage
| ![image](https://user-images.githubusercontent.com/78971099/143632597-ea57a932-a600-4611-b0e1-56ede3cd6ecd.png) | ![image](https://user-images.githubusercontent.com/78971099/143632354-eb636efd-c8c1-46a6-a7f8-a3ed3e00aaca.png) |

Fix position of arrows and button in slider on Homepage

---

src/containers/orders/cart/cart-item/cart-item.js
src/pages/login/login.js

Fix console warnings #1407

---

src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
src/pages/thanks-page/thanks-page.js

Clean console errors in nova-post and thanks-page components

clean console/1405/errors with missing dependencies in useEffect

---

src/components/app/app-theme/app.pallete.js
src/locales/en/login.json
src/locales/ua/login.json
src/pages/login/login.js
src/pages/login/login.styles.js

redesign login page

---

public/index.html

Fixed integrity error

---

src/pages/home/slider/slider-home-page.style.js

Added adaptive to slider on Home page
| ![image](https://user-images.githubusercontent.com/78971099/143941584-4c7bce1e-b08b-411b-a85e-67611bacddbf.png) | ![image](https://user-images.githubusercontent.com/78971099/143941678-9eabd53b-ebc2-4568-a245-698eb5334366.png) |

Fix adaptive slider

---

src/pages/images-constructor/images-constructor.js
src/pages/images-constructor/tests/images-constructor.spec.js

Changed translations in the constructor.

Refactor translations back, basics, bottoms, pocket, strap and position in front-end

---

src/pages/home/slider/slider-home-page.js

[HOTFIX] Rework/1437/rework main slider

---

src/components/app/app-theme/theme.js
src/routes/routes.style.js

added background-color rule. Changed dark theme color in app.pallete|

added background-color rule. Changed dark theme color in app.pallete

---

src/pages/product-details/product-images/product-images.js

Add loading for product image
|![image](https://user-images.githubusercontent.com/57355852/144874847-1399343a-c937-402a-b5da-81f573db80d1.png)|![image](https://user-images.githubusercontent.com/57355852/144874728-6dc1dacd-dcfe-4964-8564-727880a043be.png) |

Fixed product image display when opening it

---

src/tests/unit/pages/register/register-form.spec.js

Written tests for Register Form #1388

write tests for register form

---

src/components/modal/modal.js
src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/operations/order.queries.js
src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
src/containers/orders/order/your-order/order-item/order-item.js
src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
src/pages/order-history/operations/order-history.queries.js
src/pages/product-details/operations/product-details.queries.js
src/pages/product-details/product-info/product-info.js
src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
src/pages/product-details/similar-products/similar-products-item/tests/__snapshots__/similar-products-item.test.js.snap
src/pages/product-details/similar-products/similar-products.js
src/pages/product-list-page/operations/product-list.queries.js
src/pages/product-list-page/product-list-item/product-list-item.js
src/pages/wishlist/filled-wishlist/filled-wishlist.js
src/pages/wishlist/operations/wishlist.queries.js
src/pages/wishlist/wishlist-item/wishlist-item.js
src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
src/tests/unit/components/order-history-list-item/order-history-item-product.variables.js
src/tests/unit/components/your-order/your-order.spec.js

Refactored names to use translations
BE part - https://github.com/ita-social-projects/horondi_client_be/pull/964

Add translations

---

src/pages/login/login.styles.js
src/pages/register/register.styles.js

Background position on Login page and Register Page - Fixed.
***BEFORE***
***AFTER***

Fix background on Login page and Register Page

---

src/pages/product-details/product-details.js
src/pages/product-list-page/product-list-filter/price-filter/price-filter.js

Console erros/catalog

---

src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
src/containers/orders/order-history/order-history-item/order-history-item.js
src/tests/unit/components/order-history-item/order-history-item.spec.js
src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
src/tests/unit/components/order-history-list-item/order-history-item-product.variables.js

Added plug to failing page
| ** Errors page ** | 
|

Add plug to falling history page

---

src/components/app/app-theme/app.pallete.js
src/components/app/app-theme/theme.js
src/pages/home/categories-list/category-item/category-item.js
src/pages/home/categories-list/category-item/category-item.style.js
src/pages/home/categories-list/category-item/tests/category-item.spec.js

Fixed carousel design bugs: 
- on hover the text drops out of the carousel-item box;
- backgrounds according to the new design;
- hover effect according to the new design;
- refacrored category-item.styles.js.
| ![Знімок екрана (88)](https://user-images.githubusercontent.com/87911115/145589388-1349ff8e-19ad-4d19-9aa4-d9213e82b539.png) | ![Знімок екрана (89)](https://user-images.githubusercontent.com/87911115/145589551-5a033bae-0ab0-47f4-95db-c16c4416f07a.png) |

fix corousel design

---

src/pages/product-details/product-images/product-images.js

Fixed side images on product page
|  ![Screenshot (67)](https://user-images.githubusercontent.com/50491616/145585073-fdf07277-2e57-42af-a70f-6043bbf9c546.png)|  ![Screenshot (68)](https://user-images.githubusercontent.com/50491616/145585163-f275b182-f32f-41f5-b913-711b271204a2.png)|

Fixed product images

---

src/pages/materials/materials.js

Fixed console warnings on the materials page
| ![Screenshot (75)](https://user-images.githubusercontent.com/50491616/145792115-cbb32847-daaa-4f0a-9b1a-ca9f7db6e0b6.png) | ![Screenshot (76)](https://user-images.githubusercontent.com/50491616/145791744-3f8049c5-c661-483c-8925-6a9f8ef3695a.png) |

Fixed materials console warnings

---

src/locales/en/common.json
src/locales/ua/common.json

Fix models translation in filters
| ![image](https://user-images.githubusercontent.com/78971099/146090108-4aac817c-8556-4380-b882-0ef94eea0811.png) | ![image](https://user-images.githubusercontent.com/78971099/146090180-3545af40-e01f-40ee-b903-0be18d2d54b7.png) |

Fix models translation in filters

---

src/pages/product-list-page/product-list-page.styles.js

Fix title highlight in Catalog
| ![image](https://user-images.githubusercontent.com/78971099/146092609-2be09961-8c03-4ca2-ae9a-a5955c773fb9.png) | ![image](https://user-images.githubusercontent.com/78971099/146092664-ce21a60a-487d-4554-af65-83110aa01dbb.png) |

Fix title highlight in Catalog

---

src/components/model-item/model-item.js
src/pages/home/models-list/models-list.js

fix url for models on mail page

(SP:0.5)fix links for catalog on main page

---

src/containers/orders/order-history/order-history-pagination/order-history-pagination.style.js
src/index.css
src/pages/news/news-page/constants.js
src/pages/news/news-page/news-page.js
src/pages/news/news-page/test/news-page.spec.js
src/pages/news/operations/news-queries.js

Add pagination according to Figma design.
***BEFORE***
***AFTER***

Create pagination for news page

---

src/pages/news/news-item/news-item.style.js
src/pages/news/news-page/news-page.style.js

Redesign News Page for all resolutions.
***BEFORE***
***AFTER***

(SP:0.5)Fix responsive design of "News" page #838

---

src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
src/pages/product-list-page/tests/price-filter.spec.js

I added the ability to change the price filter using the input fields on the catalog page
| ![image](https://user-images.githubusercontent.com/57355852/145686341-7135f2be-dd8c-4f64-8b37-310c2ab2c0ba.png) | ![image](https://user-images.githubusercontent.com/57355852/145686380-fa88359e-4289-4578-ad32-b642f094fadf.png)|

Add functionality to price text boxes

---

src/containers/header-profile/header-profile.js

Fix console warning in the header profile component.
|         Original          | 
|  ![photo_2021-12-15_13-38-02](https://user-images.githubusercontent.com/49168997/146223667-66718ec5-a6ab-4c1d-a112-49e42452e2d2.jpg) |

Fix console warning

---

src/pages/home/contructor-preview/constructor-preview.style.js

Fixed 2nd slider
***before***
***AFTER***

(SP:0.5) Fix 2nd slider on main page

---

src/containers/footer-lists/footer-lists.js
src/containers/sidebar/sidebar-item/sidebar-item.js
src/pages/home/categories-list/categories-list.js

Fixed count per page and default page on routes in sidebar footer and categories

fixed coundPerPage in routes in sidebar footer and categories

---

package-lock.json
src/components/app/app-theme/theme.js
src/containers/orders/order-history/empty-order-history/empty-order-history.js
src/containers/orders/order-history/order-history-item/order-history-item.js
src/containers/orders/order/empty-order/empty-order.js
src/containers/orders/order/empty-order/empty-order.styles.js
src/containers/orders/order/empty-order/tests/__snapshots__/empty-order.test.js.snap
src/containers/orders/order/empty-order/tests/empty-order.test.js
src/locales/ua/order-history.json
src/pages/home/models-list/models-list.style.js
src/pages/order-history/order-history.styles.js
src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap

Fix order history ui bugs  
1) Header name  & button name
updated
origin 
2) Button name cover on hover effect 
origin
3) Order status name on UA local 
updated 
origin 
4) Order history header 
updated 
origin

fix ui bugs on order history page

---

src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/cart/cart-item/tests/cart-item.spec.js
src/pages/cart/cart.js
src/pages/images-constructor/constructor-sumbit/constructor-submit.js

Fix the problem of adding products from the catalog to the cart. 
Run together with https://github.com/ita-social-projects/horondi_client_be/pull/1002

fix checkout problem

---

src/pages/product-details/product-description/product-description.js
src/pages/product-details/product-details.js
src/pages/product-details/product-info/product-info.js
src/pages/product-details/product-info/tests/product-info.test.js
src/pages/product-details/product-info/tests/product-info.variables.js
src/pages/product-details/product-sizes/product-sizes.js
src/pages/product-details/product-sizes/tests/product-sizes.test.js
src/pages/product-details/product-submit/product-submit.js
src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
src/pages/product-details/tests/product-details.spec.js
src/tests/unit/pages/product-details/product-description/product-description.spec.js
src/tests/unit/pages/product-details/product-description/product-description.variables.js

Remove redux from product details child components

remove redux | product details

---

src/containers/products-filters-container/products-filters-container.styles.js
src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
src/pages/product-list-page/product-list-filter/product-list-filter.styles.js
src/pages/product-list-page/product-list-item/product-list-item.js
src/pages/product-list-page/product-list-item/product-list-item.style.js

Fixed styles in hover effect on button.
| ** ![зображення](https://user-images.githubusercontent.com/65071268/147392683-edde54da-4311-4cc4-8872-6bd51ef193b7.png) ** | ** ![зображення](https://user-images.githubusercontent.com/65071268/147392690-357a8e77-9c5e-43fb-9964-c0d35e0edbe5.png)** |
1.Rating stars should be above the text and price.
2. Added styles in price section: "font-weight" and "font-size".
3. Added style in item naming, should be "text-transform": "Capitalize".
4. Removed "from" before price.
| ** …

fix bugs with styles

---

src/tests/unit/pages/order-history/order-history.spec.js
src/tests/unit/pages/order-history/order-history.variables.js

My task was to rewrite the tests using RLT for the order-history.js file
| ** original screenshot ** | ** ![Знімок екрана (87)](https://user-images.githubusercontent.com/59199055/147879968-c3bd1d48-b982-4d8d-838d-bf0c0a196130.png) ** |

test was rewrited

---

src/containers/cart-header/tests/cart-header.spec.js

Rewrite tests for CartHeader component.

rewrite test

---

src/containers/checkout/checkout-form/checkout-form.js
src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
src/locales/en/profilePage.json
src/locales/ua/profilePage.json
src/pages/profile-page/constants.js
src/redux/user/user.operations.js
src/utils/checkout.js
src/utils/checkout.spec.js
src/utils/handle-profile-page.js

Address fields should auto-complete if user filled address fields in profile-page. After changing delivery type fields also should auto-complete.
|![image](https://user-images.githubusercontent.com/57355852/148748538-1dea4af0-9440-4a36-adfa-f9295ab81f71.png) | ![image](https://user-images.githubusercontent.com/57355852/148748634-bebbf6de-1b04-40cd-8744-f671e1590b12.png) |

Added address auto-completion on checkout

---

src/components/app-header/app-header.styles.js
src/containers/checkout/checkout-form/checkout-form.styles.js
src/containers/orders/order/your-order/order-item/order-item.js
src/containers/orders/order/your-order/your-order.js
src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
src/pages/product-details/similar-products/similar-products.js
src/pages/product-details/similar-products/similar-products.styles.js
src/pages/product-list-page/product-list-item/product-list-item.js
src/pages/product-list-page/product-list-item/product-list-item.style.js

Сorrect the display of the component call us (when we switch to the Ukrainian language, the component begins to take 2 lines) and fix the display of the currency icon in the product catalog and in your order list.
| ** ![1 до](https://user-images.githubusercontent.com/59199055/149336305-e1a3571c-ebc7-4285-935d-3f6aebb33893.jpg) ** | ** ![1 після](https://user-images.githubusercontent.com/59199055/149336347-efd4419d-bad5-424c-840c-8b509e6e8732.jpg) ** |
| ** ![2 до](https://user-images.githubusercontent.com/59199055/149336401-f3242339-0435-4c06-8b39-4ab23f7d59a4.jpg) …

fix 'call us' component and currency icon in catalog

---

src/containers/sidebar/sidebar.js

Fix console warning in sidebar component

fix console warning in sidebar

---

src/pages/wishlist/operations/wishlist.mutations.js

fix translations on wish list after deleting one product
| ![image](https://user-images.githubusercontent.com/64384450/149961897-92f4e98e-7ffa-4780-8f2e-8d9e4e33d0ee.png)| ![image](https://user-images.githubusercontent.com/64384450/149961970-b32f4f74-80b1-434e-93bf-25e30d4c5d15.png) 
|

fixWishListQueries

---

src/containers/search-bar/search-bar.js

cant enter any symbol on searchBar 
| 
|![image](https://user-images.githubusercontent.com/64384450/150336478-1eaebe63-ea9a-457c-b255-94734ba32e68.png)|

fixSearchBar

---

src/containers/sidemenu-right-bar/sidemenu-right-bar.js

Previously, clicking on the wishlist in the burger, menu did not close. Now closing.

When you click on the wishlist in the burger menu, it closes. 

---

src/pages/product-details/operations/product-details.queries.js
src/pages/product-details/product-images/product-images.js
src/pages/product-details/product-info/product-info.js

fixed image sizes
|![image](https://user-images.githubusercontent.com/27858056/152642661-1f9588b6-adfc-4bf0-a7e5-b3c88561dd94.png)|![image](https://user-images.githubusercontent.com/27858056/152642587-eb0fe720-ca89-4b06-8925-162635382637.png)|
|![image](https://user-images.githubusercontent.com/27858056/152642716-399fa0dc-bdee-4bd8-81fc-08bd54b13cf1.png)|![image](https://user-images.githubusercontent.com/27858056/152642702-f18a9c44-072f-4814-a85d-390b0b54aba9.png)|

fixed image sizes

---

README.md

add images of new team

---

src/pages/images-constructor/images-constructor.style.js

adaptive design for constructor page
|![image](https://user-images.githubusercontent.com/80056472/154101234-5eda0e96-066c-45dd-b0da-2976dba84b17.png)|![image](https://user-images.githubusercontent.com/80056472/154101283-5f96f850-41b0-43eb-b674-3ec84521d084.png)|

adaptive design for constructor page

---

src/components/app-footer/app-footer.styles.js
src/containers/footer-lists/footer-lists.styles.js
src/containers/social-links/social-links.styles.js
src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
src/pages/wishlist/wishlist-item/wishlist-item.styles.js

Made adaptive design for wishlist & footer

adaptive design for wishlist & footer

---

src/pages/business-page/business-page.style.js
src/pages/materials/materials.style.js

Design/adaptive for Business pages

---

src/containers/checkout/checkout-form/tests/checkout-form.spec.js
src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/cart/cart-item/tests/cart-item.spec.js
src/containers/orders/cart/filled-cart/filled-cart.js
src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
src/containers/orders/operations/getConstructorByModel.query.js
src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
src/containers/orders/order/your-order/order-item/order-item.js
src/hooks/use-cart.js
src/locales/en/common.json
src/locales/ua/common.json
src/pages/cart/cart.js
src/pages/cart/operations/cart.mutations.js
src/pages/images-constructor/constructor-sumbit/constructor-submit.js
src/pages/images-constructor/constructor-sumbit/tests/constructor-submit.spec.js
src/pages/images-constructor/images-constructor.js
src/pages/images-constructor/operations/getAllConstructors.queries.js
src/pages/images-constructor/operations/getConstructorByModel.queries.js
src/pages/images-constructor/tests/images-constructor.spec.js
src/pages/images-constructor/use-constructor-loader.js
src/pages/order-history/operations/order-history.queries.js
src/pages/product-details/similar-products/similar-products.js
src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
src/utils/productDetails.js

Fixed order creation from constructor

Fixed order creation from constructor for logged in users

---

src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/order/your-order/order-item/order-item.js
src/pages/images-constructor/use-constructor-loader.js

Fixed cart item

---

src/pages/product-details/product-details.styles.js
src/pages/product-details/product-images/product-images.styles.js
src/pages/product-details/product-info/product-info.styles.js
src/pages/product-details/product-sizes/product-sizes.js
src/pages/product-details/product-sizes/product-sizes.styles.js

Made hotfixes on product detail page.
| ![Screenshot_36](https://user-images.githubusercontent.com/89595428/154314224-aadea976-2078-4400-b638-bd2b7e95504c.png) | ![Screenshot_39](https://user-images.githubusercontent.com/89595428/154317712-7138b94f-b18f-4d60-b468-e99f869a4253.png) |
| ![image](https://user-images.githubusercontent.com/89595428/154317227-5c5825b9-e285-484b-930a-589b13a5f573.png) | ![Screenshot_38](https://user-images.githubusercontent.com/89595428/154317322-79452221-2eea-42b3-8860-27ccde8e9c18.png) |
|         Original          |         Updated …

change styles of product details page, change size button

---

src/pages/product-details/comments/comments-item/comments-item.styles.js
src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.styles.js

Added styles to prevent situations when the text of comment is out of scope frame and overlaps on button when entered a lot of symbols.
|         Original          | 
|        Updated         |

Fixed line overflow in comments

---

src/containers/chat/chat.js
src/containers/chat/chat.style.js
src/index.css

Revert "Facebook Messenger widget appears in 5 seconds late"

---

src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.js
src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.styles.js

Switch verified purchase icon in reply to same as in comments.
| ![зображення](https://user-images.githubusercontent.com/56231198/158983206-56085f8a-20f8-4b56-a7ac-71aebeaa9cbd.png) | ![зображення](https://user-images.githubusercontent.com/56231198/159178017-7d6bab23-2d52-47ec-b8bd-04fb220cbe60.png) |

Fixed verified purchase icon in reply

---

src/pages/home/models-list/models-list.js
src/pages/home/models-list/models-list.style.js

Fixed incorrect view of Products container on mobile view
| ![ test before](https://user-images.githubusercontent.com/45914032/160080199-28fe1b80-4824-4ee3-b07e-9ed761b77f19.png) | ![after 2](https://user-images.githubusercontent.com/45914032/160080275-317f18f7-c6d0-4088-8eb0-ad2f4236770b.png)|

fixed incorrect view of products on mobiles

---

src/components/app/app-theme/theme.js

Changed chat button teme color and background color in dark mode
| ![image](https://user-images.githubusercontent.com/59802802/161951190-3bce1374-2081-408d-b8fa-fd8cc3f563db.png) | ![original2](https://user-images.githubusercontent.com/59802802/161951265-9ca41638-15de-4af0-8ba4-278042ee70f6.gif) |

Fixed incorrect color of chat button in dark mode

---

src/redux/user/user.operations.js

Deleted one of the two "confirmed", added configs
| ![errror before](https://user-images.githubusercontent.com/100776036/161568389-89e204da-51d2-4297-b328-8fe12909133a.png) | ![after](https://user-images.githubusercontent.com/100776036/161568417-4c670cdf-889b-4da1-b220-a185f6e57c9d.png) |

 After user info on the user page crashes when clicking on the button Save

---

src/components/app/app-theme/app.pallete.js
src/components/app/app-theme/theme.js
src/components/auth-form/auth-form-button/auth-form-button.styles.js
src/components/modal/modal.styles.js
src/containers/checkout/checkout-form/checkout-form.styles.js
src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
src/pages/home/contructor-preview/constructor-preview.js
src/pages/home/contructor-preview/constructor-preview.style.js
src/pages/home/models-list/models-list.style.js
src/pages/home/models-list/tests/models-list.spec.js
src/pages/home/slider/slider-home-page.style.js
src/pages/images-constructor/constructor-sumbit/constructor-submit.styles.js
src/pages/news/news-detail/news-detail.style.js
src/pages/product-details/comments/comments.styles.js
src/pages/thanks-page/thanks-card/thanks-card.styles.js
src/pages/wishlist/wishlist-item/wishlist-item.styles.js
src/tests/unit/components/thanks-card/thanks-card.spec.js
src/tests/unit/pages/thanks-page/thanks-page.spec.js

Problems : 
There are 2 types of buttons on the client side. But in different components they have different styles and hover effects.
Some buttons of the same type have a hover effect when hovering, while others do not.
Solution:
The colors of the buttons are set according to the layout where they differed. Same hovers are setted for buttons of the same type.
Fixed 'font-size'' of 'Confirm order' button in Checkout Process page.
| ![favoriteButtons](https://user-images.githubusercontent.com/59802802/162404198-7d7f7ae9-6802-45c0-bd5e-6c4d7c93efe9.gif) | ![favoriteButtonsFix](https://user-images.githubusercontent.com/59802802/162404410-24b87f7d-3006-4ea0-aa14-acc8a6d79def.gif) …

Changed buttons color and hover effect according to figma layout

---

src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/cart/filled-cart/filled-cart.js
src/containers/orders/operations/getConstructorById.queries.js
src/containers/orders/operations/getConstructorByModel.query.js
src/containers/orders/order/your-order/order-item/order-item.js
src/hooks/tests/use-cart.spec.js
src/hooks/use-cart.js
src/locales/en/common.json
src/locales/ua/common.json
src/pages/images-constructor/constants.js
src/pages/images-constructor/images-constructor.js
src/pages/images-constructor/images-constructor.style.js
src/pages/images-constructor/operations/getAllConstructors.queries.js
src/pages/images-constructor/operations/getConstructorByModel.queries.js
src/pages/images-constructor/tests/images-constructor.spec.js
src/pages/images-constructor/use-constructor-loader.js
src/utils/constructor.js

Refactored constructor prices

---

src/pages/wishlist/filled-wishlist/filled-wishlist.js

If you add new products to wishlist, it will be at the bottom of a list.
| ** ![зображення](https://user-images.githubusercontent.com/56231198/163191347-cfbc6c5e-1659-4109-9a06-9937abf354e0.png) ** | ** ![зображення](https://user-images.githubusercontent.com/56231198/163189616-f4cebdc0-575d-4edb-9cfd-95a9a1ab04e7.png) ** |

fix bug with list order

---

src/redux/user/tests/user.sagas.spec.js
src/redux/user/user.operations.js
src/redux/user/user.sagas.js
src/utils/client.js

Fixed an issue where we could not login to the account when entering the correct data.

Fix logination bug

---

src/pages/home/models-list/models-list.style.js

Fixed styles at models-list.style
| ![image](https://user-images.githubusercontent.com/80908916/166939534-d8b86d14-ad52-4382-b76b-b51bdfd15b07.png) | ![image](https://user-images.githubusercontent.com/80908916/166939642-1f525a3f-111a-4788-ad9d-136d45c75ada.png) |

was_fixed-slider_doesnt_move_to_our_model_section

---

src/hooks/use-cart.js

|![before](https://user-images.githubusercontent.com/100776036/167680869-a2c97376-c023-42b2-b93f-4f6712c1f6cd.png) | ![after](https://user-images.githubusercontent.com/100776036/167680894-64e4e83d-acd8-4d53-8623-a9ba9f471ba6.png) |

[Cart] New product added to the Cart is located at the bottom of the list

---

src/containers/checkout/checkout-form/checkout-form.styles.js
src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/cart/cart-item/cart-item.styles.js
src/containers/orders/order/order-table/order-table.styles.js
src/containers/orders/order/your-order/order-item/order-item.js

I have fixed incorrect images photo size and product name position to currency.
| ![image](https://user-images.githubusercontent.com/80908916/167616790-9dd6c020-040b-4ea1-aee5-040f00844550.png) | ![image](https://user-images.githubusercontent.com/80908916/167616896-8052bae0-c8b0-40fe-8c39-e399a6d71925.png) |
|![image](https://user-images.githubusercontent.com/80908916/167617138-b724463d-c472-4dab-a20d-a82d517028e0.png) | ![image](https://user-images.githubusercontent.com/80908916/167617201-35044721-5882-469d-bb02-5a4953c429f8.png) |

Bug fix/1915/order history/incorrect images photo size

---

src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/cart/cart-item/tests/cart-item.variables.js
src/containers/orders/operations/getConstructorByModel.query.js
src/containers/orders/operations/order.queries.js

I've added to the queries new "medium" image and changed "thumbnail". So,bug was fixed.

Fixed the image quality

---

src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.styles.js
src/containers/search-bar/search-bar.js

Fixed styles of button and fixed bug when we click on button DETAILS this product does not open
| ![before1](https://user-images.githubusercontent.com/100776036/170092516-be12ab14-1eee-4174-826e-6905cea59e48.png)| ![after1](https://user-images.githubusercontent.com/100776036/170093038-2dece014-ccbe-4642-990b-78dae336fe1f.png)|

Style of search results does not match the overall style of the web-site

---

src/locales/en/home.json
src/locales/ua/home.json
src/pages/home/slider/slider-home-page.js

| ![before](https://user-images.githubusercontent.com/100776036/169849793-bf4ddee2-fd1f-4890-a8c4-eb1405f7af38.png) | ![after](https://user-images.githubusercontent.com/100776036/169849853-76a6c745-aa11-4216-b549-99907d7ebc45.png) |

Absence of 'Shop now' button

---

src/redux/user/user.sagas.js

When you logout, now tokens are deleted from localStorage.

fix logout

---

src/components/number-input/number-input.styles.js
src/pages/business-page/business-page.style.js
src/pages/gift-certificate/certificate-checkbox/certificate-checkbox.styles.js
src/pages/gift-certificate/gift-certificate.styles.js
src/pages/register/register-from/register-form.styles.js
src/pages/register/register.js
src/redux/user/user.sagas.js

styles fixed

---

src/pages/news/news-detail/news-detail.style.js

| ![Screenshot 2022-06-02 at 21-46-40 Build software better together](https://user-images.githubusercontent.com/49586997/171703982-0b9f5d38-77f1-432e-b61a-f918992b7002.png) |  |

fix breadcrumbs visibillity

---

src/containers/header-profile/header-profile.js

login with google fixed

---

src/containers/my-certificates/certificate-table/certificate-table.styles.js
src/containers/my-certificates/cetrificate-item/certificate-item.styles.js
src/containers/my-certificates/filled-certificates/filled-certificates.styles.js

| ![before](https://user-images.githubusercontent.com/100776036/172065891-a26b9c92-e559-411a-9146-386abf81231f.png) | ![after2](https://user-images.githubusercontent.com/100776036/172065894-e9dbf4c5-e8bd-4ec2-b3d1-76404ed0143f.png) |

In "My certificates" write responsive page

---

src/containers/orders/cart/cart-item/cart-item.styles.js
src/containers/orders/order/order-table/order-table.styles.js

Now item row in cart looks correct, responsive as well
| ![Clip2net_220606153629](https://user-images.githubusercontent.com/49586997/172162010-8c326ed0-2813-4d6e-be91-578ec92cc991.png) | ![Clip2net_220606153604](https://user-images.githubusercontent.com/49586997/172161977-0c4d8430-aaff-4e14-9520-05cf8fe96aa4.png) |

cart image offset fix

---

src/containers/chat/chat.js

Facebook login with fb messenger fixed.

login facebook conflict fixed

---

src/components/constructor-canvas/constructor-canvas.js
src/locales/ua/common.json
src/pages/images-constructor/constants.js
src/pages/images-constructor/images-constructor.js
src/pages/images-constructor/operations/getConstructorByModel.queries.js
src/pages/images-constructor/use-constructor-loader.js

Replaced hardcoded basePrice by queried it from DB

added basePrice to constructor

---

src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
src/containers/orders/order-history/order-history-item/order-history-item.styles.js
src/containers/orders/order-history/order-history-table/order-history-table.js
src/containers/orders/order-history/order-history-table/order-history-table.style.js
src/pages/order-history/operations/order-history.queries.js
src/pages/order-history/order-history.styles.js

1. Fixed blurry images in the order history page.
2. Fixed problem with the rendering of the canvas image.
3. Created adaptive design for order history page.
| ![image](https://user-images.githubusercontent.com/80908916/173691402-cd73fec4-d8ab-4173-b583-98cf71823424.png) |![image](https://user-images.githubusercontent.com/80908916/173691509-6f8b77aa-653e-4742-9c8d-89d3cea26391.png) |
https://user-images.githubusercontent.com/80908916/173693010-b5e296ce-d3ba-44fb-8f91-a54f2c4f48c1.mp4

fixed bugs and created adaptive design for order history page

---

src/components/facebook-log-in-btn/facebook-button.js
src/containers/chat/chat.js

facebook env changes

---

src/containers/chat/active-messenger/active-messenger.js
src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
src/containers/snackbar/snackbar.js
src/pages/answers-questions-page/answers-questions-page.js
src/pages/news/news-item/news-item.js
src/pages/news/news-item/news-item.style.js
src/pages/product-details/comments/comments.js
src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
src/pages/product-list-page/product-list-page.js
src/routes/routes.js
src/utils/eyeToggle.js

Fix SonarCloud code-smells Front-end on repository.

---

src/components/facebook-log-in-btn/facebook-button.js
src/pages/register/tests/register.test.js
src/tests/unit/pages/login/login.spec.js
src/tests/unit/pages/register/register-form.spec.js

Bugfix facebook login

---

src/containers/search-bar/search-bar.js
src/containers/search-bar/search-bar.styles.js
src/containers/search-bar/tests/search-bar.spec.js

created clear icon for home search.
|![before](https://user-images.githubusercontent.com/63456632/175981009-7f9db13c-f7d5-4aba-b131-7995609333b3.png) | ![image](https://user-images.githubusercontent.com/63456632/175981683-63f5b396-ee4f-4296-af0e-0e09f53818e8.png)|

create clear icon at home search

---

src/containers/checkout/checkout-form/checkout-form.js
src/redux/order/order.operations.js
src/utils/checkout.js

Displayed price without discount within promo code was used

---

src/pages/home/contructor-preview/constructor-preview.js
src/pages/home/contructor-preview/constructor-preview.style.js

Fixed horizontal scroll on less than 769px and content visibility between 421px and ~600px.

Fix the video overflow and content visibility in the CREATE BY YOURSELF section

---

Dockerfile
azure-pipelines.yml

fix dockerfile

---

Dockerfile

fix dockerfile again

---

src/redux/user/tests/user.sagas.spec.js
src/redux/user/user.sagas.js

Added confirmation after login with google, so block "confirm email" will not appear after every login with google
| ![176482675-79e4f356-f33e-43e6-b5ab-ef32fdfd2bc6](https://user-images.githubusercontent.com/97129041/177517642-e3414eae-1609-4757-a727-3cc05687d1f4.png) | ![newGoogleLogin](https://user-images.githubusercontent.com/97129041/177517696-d1eb2d51-27b7-44ea-a85c-67d3956fbdb1.png) |
Checklist

After entering via google customer has to be confirmed

---

src/containers/header-profile/header-profile.js
src/containers/header-profile/header-profile.styles.js

fixed vertical scroll when dropdown toggle.
| ![image](https://user-images.githubusercontent.com/63456632/178098939-14742edf-8695-4437-b05d-bb227f55b5cf.png)|![image](https://user-images.githubusercontent.com/63456632/178098958-884d0592-9d05-4788-8de7-b7298d30d0cd.png) |

fixed vertical scroll when dropdown toggle

---

src/components/app-header/app-header.js
src/components/app-header/app-header.styles.js
src/components/app-header/tests/app-header.spec.js
src/containers/sidebar/sidebar.styles.js
src/containers/sidemenu-right-bar/sidemenu-right-bar.js
src/containers/sidemenu-right-bar/sidemenu-right-bar.styles.js
src/containers/social-links/social-links.styles.js
src/containers/theme/index.js
src/containers/theme/tests/theme-component.spec.js
src/containers/theme/theme-component.js
src/containers/theme/theme.styles.js
src/locales/en/header.json
src/tests/unit/components/sidemenu-right-bar/sidemenu-right-bar.spec.js

Added component for swiching theme and rewrote some styles 
| !![originalSide](https://user-images.githubusercontent.com/97129041/179395486-5352eae4-edce-48ae-9d15-b9593d6773e7.png)| ![newSide](https://user-images.githubusercontent.com/97129041/179395494-bc4af69c-9576-4939-94d4-53f7464a5ba2.png)|

Add possibility to change theme on mobile

---

src/containers/currency/currency.styles.js

change currency size
| ![image](https://user-images.githubusercontent.com/63456632/179559792-f37b4e5c-512c-40e1-9839-73f049a40015.png)|![image](https://user-images.githubusercontent.com/63456632/179568291-61cd6708-997d-44ee-b158-0b9b86b835c6.png) ![image](https://user-images.githubusercontent.com/63456632/179560063-775a85a2-626e-4cbd-8b94-de73f7248f35.png) |

change currency size

---

jest.config.js
package-lock.json
package.json
public/index.html
src/components/facebook-log-in-btn/facebook-button.js
src/containers/chat/chat.js
src/containers/chat/chat.style.js
src/containers/chat/helperFunc.js
src/containers/chat/tests/chat.spec.js
src/containers/chat/tests/chatLoader.spec.js
src/containers/checkout/checkout-form/tests/checkout-form.spec.js
src/containers/header-profile/header-profile.js
src/containers/search-bar/tests/search-bar.spec.js
src/index.css
src/pages/register/tests/register.test.js
src/tests/unit/pages/login/login.spec.js
src/tests/unit/pages/register/register-form.spec.js

Fix facebook with facebook chat conflict

Facebook login with chat

---

src/components/app/app.js
src/configs/index.js
src/containers/cart-header/cart-header.js
src/containers/cart-header/tests/cart-header.spec.js
src/containers/checkout/checkout-form/tests/checkout-form.spec.js
src/containers/checkout/checkout.js
src/containers/checkout/tests/checkout.spec.js
src/containers/wishlist-header/tests/wishlist-header.spec.js
src/containers/wishlist-header/wishlist-header.js
src/context/cart-context.js
src/context/wishlist-context.js
src/hooks/tests/use-cart.spec.js
src/hooks/tests/use-wishlist.spec.js
src/hooks/use-cart.js
src/hooks/use-wishlist.js
src/pages/cart/cart.js
src/pages/images-constructor/constructor-sumbit/constructor-submit.js
src/pages/images-constructor/constructor-sumbit/tests/constructor-submit.spec.js
src/pages/images-constructor/images-constructor.js
src/pages/product-details/product-submit/product-submit.js
src/pages/wishlist/filled-wishlist/filled-wishlist.js
src/pages/wishlist/filled-wishlist/tests/filled-wishlist.spec.js
src/pages/wishlist/tests/wishlist.spec.js
src/redux/common-store/common.actions.js
src/redux/common-store/common.reducer.js
src/redux/user/tests/user.sagas.spec.js
src/redux/user/user.sagas.js
src/services/local-storage.service.js

Added correct initial state for cart and wishlist. Also removed redundant code.

Added correct initial state for cart and wishlist

---

src/pages/thanks-page/thanks-card/thanks-card.styles.js
src/pages/thanks-page/thanks-page.styles.js

fixed thank you page styles.
| ![image](https://user-images.githubusercontent.com/63456632/182889185-141aab9d-4474-4efb-9314-1bc790698906.png)| ![image](https://user-images.githubusercontent.com/63456632/182889343-616e3011-8b21-4fd3-a577-e4262429b5ec.png)|

fixed thank you page styles.

---

src/containers/checkout/checkout-form/checkout-form.js
src/containers/checkout/checkout-form/delivery/worldwide/worldwide.js

Changed price for the order if  promo code is used and payment method is a card, fixed a few warnings

Price at fondy display without a discount

---

src/pages/my-certificates/my-certificates.js
src/pages/my-certificates/operations/my-certificates.queries.js
src/tests/unit/pages/my-certificates/my-certificates.variables.js

preventing caching of certificates when changing the user

preventing caching of certificates when changing the user

---

src/containers/orders/cart/filled-cart/filled-cart.js
src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
src/hooks/tests/use-cart.spec.js
src/hooks/tests/use-currency.spec.js
src/hooks/use-cart.js
src/hooks/use-currency.js

Fixed negative total price with certificate while changing currency to usd

fixed bug with certificate value

---

src/components/confirm-dialog/confirm-dialog.js
src/components/confirm-dialog/confirm-dialog.styles.js
src/components/confirm-dialog/index.js
src/components/modal/modal.js
src/components/modal/modal.styles.js
src/components/modal/tests/modal.spec.js
src/containers/modal-gift-certificate/index.js
src/containers/modal-gift-certificate/modal-gift-certificate.js
src/containers/modal-gift-certificate/modal-gift-certificate.styles.js
src/containers/modal-gift-certificate/tests/mocal-gift-certificate.variables.js
src/containers/modal-gift-certificate/tests/modal-gift-certificate.spec.js
src/containers/my-certificates/certificate-table/certificate-table.js
src/containers/my-certificates/cetrificate-item/certificate-item.js
src/containers/my-certificates/filled-certificates/filled-certificates.js
src/containers/orders/order/order-table/order-table.js
src/containers/orders/order/order-table/tests/order-table.test.js
src/containers/orders/order/order-table/tests/order-table.variables.js
src/locales/en/modal.json
src/locales/ua/modal.json
src/pages/gift-certificate/operations/gift-certificate.mutations.js
src/pages/images-constructor/images-constructor.js
src/pages/wishlist/filled-wishlist/filled-wishlist.js
src/validators/email.js

Created pop up after clicking on gift certificate icon

Created pop up after clicking on gift certificate icon

---

src/locales/en/thanksPage.json
src/locales/ua/thanksPage.json
src/pages/certificate-thanks-page/certificate-thanks-card/certificate-thanks-card.js
src/pages/certificate-thanks-page/certificate-thanks-card/certificate-thanks-card.styles.js
src/pages/certificate-thanks-page/certificate-thanks-page.js
src/pages/gift-certificate/gift-certificate.js
src/tests/unit/components/certificate-thanks-card/certificate-thanks-card.spec.js
src/tests/unit/pages/certificate-thanks-page/certificate-thanks-page.spec.js

Certificate thanks page is displayed after payment

Certificate thanks page is not displayed after payment

---

src/components/scroll-to-top/scroll-to-top.js
src/components/scroll-to-top/tests/scroll-to-top.spec.js
src/routes/routes.js

Scroll to top when you navigate another page.

scroll to top after navigate another page

---

src/containers/modal-gift-certificate/modal-gift-certificate.js
src/containers/modal-gift-certificate/modal-gift-certificate.styles.js
src/containers/modal-gift-certificate/tests/mocal-gift-certificate.variables.js
src/containers/modal-gift-certificate/tests/modal-gift-certificate.spec.js
src/containers/modal-successful-gift/modal-successful-gift.js
src/containers/my-certificates/filled-certificates/filled-certificates.js
src/locales/en/modal.json
src/locales/ua/modal.json

Added successfully gifted certificate modal.

added successfully gifted certificate modal

---

src/containers/modal-gift-certificate/modal-gift-certificate.js
src/containers/modal-gift-certificate/tests/modal-gift-certificate.spec.js
src/containers/my-certificates/filled-certificates/filled-certificates.js
src/pages/my-certificates/my-certificates.js
src/tests/unit/pages/my-certificates/my-certificates.spec.js
src/tests/unit/pages/my-certificates/my-certificates.variables.js

Certificates attached to email

Certificates attached to email

---

src/components/auth-form/auth-form-wrapper/auth-form-wrapper.styles.js
src/pages/recovery/recovery.js
src/pages/recovery/recovery.styles.js
src/redux/user/tests/user.sagas.spec.js
src/redux/user/user.sagas.js
src/utils/handle-recovery-page.js

Added password recovery error

---

src/components/auth-form/auth-form-button/auth-form-button.js
src/pages/login/login.js
src/pages/new-password/new-password.js
src/pages/new-password/tests/new-password.test.js
src/pages/recovery/recovery.js
src/pages/recovery/tests/recovery.test.js
src/pages/register/register-from/register-form.js
src/tests/unit/components/auth-form/auth-form-button/auth-form-button.spec.js
src/tests/unit/pages/login/login.spec.js
src/tests/unit/pages/register/register-form.spec.js
src/utils/handle-new-password.js
src/utils/handle-recovery-page.js
src/validators/new-password.js

- Improve auth-form-button component
- refactor login, registration, recovery and new password pages
| ![image](https://user-images.githubusercontent.com/79531224/195809040-532ed6f5-1160-43b3-9c45-8ae3aac09618.png) |![image](https://user-images.githubusercontent.com/79531224/195808985-910dd3d2-0c93-411f-8f42-c81d50499d3b.png) |

Feature/2169/fix loader in login page 

---

src/pages/thanks-page/thanks-page.js
src/redux/order/order.actions.js
src/redux/order/order.operations.js
src/redux/order/order.sagas.js
src/redux/order/order.types.js
src/redux/order/tests/order.actions.test.js
src/redux/order/tests/order.sagas.test.js
src/redux/order/tests/order.variables.js
src/tests/unit/pages/thanks-page/thanks-page.spec.js
src/utils/checkout.js

Sending email after successful payment.

sending email after successful payment

---

src/components/app-header/app-header.js
src/components/app-header/tests/app-header.spec.js
src/containers/cart-header/cart-header.js
src/containers/cart-header/tests/cart-header.spec.js
src/containers/checkout/checkout-form/tests/checkout-form.spec.js
src/containers/checkout/checkout.js
src/containers/checkout/tests/checkout.spec.js
src/containers/orders/cart/filled-cart/filled-cart.js
src/containers/orders/order/your-order/your-order.js
src/context/cart-context.js
src/hooks/tests/use-cart.spec.js
src/hooks/use-cart.js
src/pages/cart/cart.js
src/pages/images-constructor/constructor-sumbit/tests/constructor-submit.spec.js
src/pages/product-details/product-submit/tests/product-submit.test.js
src/pages/thanks-page/thanks-page.js
src/redux/common-store/common.actions.js
src/redux/common-store/test/common.action.spec.js
src/redux/common-store/test/common.reducer.spec.js
src/tests/unit/components/your-order/your-order.spec.js
src/tests/unit/pages/thanks-page/thanks-page.spec.js

expanded useCart hook

---

src/containers/checkout/checkout-form/tests/checkout-form.spec.js
src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/cart/cart-item/tests/cart-item.spec.js
src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
src/containers/orders/operations/order.queries.js
src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
src/containers/orders/order/order-table/tests/order-table.test.js
src/containers/orders/order/your-order/order-item/order-item.js
src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.styles.js
src/containers/search-bar/tests/search-bar.spec.js
src/hooks/use-debounce.js
src/hooks/use-product-image.js
src/pages/materials/materials.js
src/pages/product-details/product-images/product-images.js
src/pages/product-details/tests/product-images.spec.js
src/pages/product-list-page/product-list-item/product-list-item.js
src/pages/product-list-page/product-list-item/product-list-item.style.js
src/pages/wishlist/filled-wishlist/filled-wishlist.js
src/pages/wishlist/wishlist-item/tests/wishlist-item.spec.js
src/pages/wishlist/wishlist-item/tests/wishlist-item.variables.js
src/pages/wishlist/wishlist-item/wishlist-item.js
src/pages/wishlist/wishlist-item/wishlist-item.styles.js
src/tests/unit/components/order-history-item/order-history-item.spec.js
src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
src/tests/unit/components/your-order/your-order.spec.js
src/tests/unit/pages/order-history/order-history.spec.js

Added useProductImage hook , if a product doesn't have an image everywhere is showing a default placeholder. Removing from cart and wishlist deleted products

Added useProductImage hook

---

src/pages/confirmation/confirmation.styles.js
src/routes/routes.style.js

Fixed image style for correct view in different graphics display resolution.
Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2170
Also changed position of “welcome” message form.
|**![image](https://user-images.githubusercontent.com/34419998/198120174-7aad2303-ae7b-4906-bfd7-979fde36e16b.png)**|**![image](https://user-images.githubusercontent.com/34419998/198120011-19f35550-1724-464f-bd97-be2b647ffa0a.png)**|

Change image position/height on successful registration page

---

src/containers/orders/cart/cart-item/cart-item.js
src/hooks/use-cart.js

Сart maximum call depth

---

src/components/auth-form/auth-form-button/auth-form-button.styles.js
src/components/auth-form/auth-form-heading/auth-form-heading.styles.js
src/pages/recovery/recovery.js
src/pages/recovery/recovery.styles.js

| ![image](https://user-images.githubusercontent.com/94409173/196944673-53409a53-2304-45b3-aa3d-21edc58efe19.png) | ![image](https://user-images.githubusercontent.com/94409173/196944780-c70829b3-557f-428d-970e-8f64f09e0a1c.png) |

Fix the email validation error message on the recovery page #2130

---

src/components/app-header/app-header.styles.js
src/containers/search-bar/search-bar.styles.js

|![image](https://user-images.githubusercontent.com/94409173/199208837-07a2cae2-b3f5-4b68-b713-3b0a193a8f90.png) | ![image](https://user-images.githubusercontent.com/94409173/199208894-dd799572-711c-4b6b-881c-855c3080e745.png) |

Fix header styles #2156

---

src/pages/home/categories-list/category-item/category-item.style.js

Fixed image background in carousel with items.
Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2196
|**![image](https://user-images.githubusercontent.com/34419998/199031854-5e2651d3-de8e-430b-8285-18e4c3f703a1.png)**|**![image](https://user-images.githubusercontent.com/34419998/199031126-6d2f7b8f-2303-46bc-8650-afe60ae31155.png)**|

Fixed image background in carousel

---

src/pages/register/register.styles.js

| ![image](https://user-images.githubusercontent.com/94409173/199277213-2ac2cf22-29cb-4374-97e4-f4988fa89999.png) | ![image](https://user-images.githubusercontent.com/94409173/199277159-bec744de-9a68-43c6-ab68-0d1fa0724e38.png) |

Fix styles in confirm email page

---

src/containers/sidebar/sidebar-item/sidebar-item.js
src/containers/sidebar/sidebar-item/sidebar-items.styles.js
src/pages/product-details/product-details.js
src/pages/product-details/product-details.styles.js

Added pointer at product page to AddToFafourite button and fixed pointer at sidebar

Add pointer at product page

---

src/pages/profile-page/profile-page.js

Disabled email editing for users

Made user unable to change email

---

src/containers/orders/cart/filled-cart/filled-cart.styles.js

| ![image](https://user-images.githubusercontent.com/94409173/200175666-5b7e3bf8-59b0-4b02-9ef7-551ff7063121.png) | ![image](https://user-images.githubusercontent.com/94409173/200175772-31e9db6b-84e3-4340-a22d-21af83d8f696.png) |

[Cart] Fix styles in Cart page 

---

src/components/accordion/accordions.style.js
src/pages/answers-questions-page/answers-questions-page.js
src/pages/answers-questions-page/answers-questions-page.style.js

Add spaces beetwen accordion and fixed border
|         **Original**          |
| ![image](https://user-images.githubusercontent.com/63456632/200364043-087b3c3a-3e8c-4500-9f26-ed4378bbf077.png) 
|         **Updated**         |

fixed spaces beetwen acordion and border

---

src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/operations/getConstructorByModel.query.js
src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
src/containers/sidebar/sidebar.js
src/locales/en/common.json
src/locales/ua/common.json
src/pages/images-constructor/images-constructor.js
src/pages/images-constructor/operations/getAllConstructors.queries.js
src/pages/images-constructor/operations/getConstructorByModel.queries.js
src/pages/images-constructor/tests/images-constructor.spec.js
src/pages/images-constructor/tests/images-constructor.variables.js
src/pages/images-constructor/use-constructor-loader.js
src/tests/unit/components/sidebar/sidebar.spec.js
src/utils/constructor.js

refactored constructor

---

src/containers/orders/order/your-order/order-item/order-item.js

Fixed product image in order item

---

src/components/app/app-theme/app.pallete.js
src/pages/product-details/product-images/product-images.styles.js

Changed size of plugs and images in the carousel.
Also, changed box-shadow color and color of text.
Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2209
|**![image](https://user-images.githubusercontent.com/34419998/200442057-afbb50b9-3bac-4caf-858e-50d538b0d670.png)**|**![image](https://user-images.githubusercontent.com/34419998/200442089-96698d86-e0d5-4b70-9f8b-b95d36ac0f6e.png)**|
|**![image](https://user-images.githubusercontent.com/34419998/200442109-120fd45c-ada9-4c71-9fca-4be7d69f0526.png)**|**![image](https://user-images.githubusercontent.com/34419998/200442118-4a6eee4b-0c8e-41bd-b94e-9fdc16f5408e.png)**| …

Changed size of plugs, color of text and box-shadow color

---

src/components/app-header/app-header.styles.js
src/containers/search-bar/search-bar.styles.js
src/pages/confirmation/confirmation.styles.js

Fix adaptivity on confirmation page
Fix some header search bar styles
| ** ![image](https://user-images.githubusercontent.com/56231198/201322768-a23c4722-0d6f-4364-9781-4f611c8e2929.png) ** | **![image](https://user-images.githubusercontent.com/56231198/201322706-d4a1b5bd-5b24-4e41-acee-cf18edff1e13.png) ** |

fix confirmation page/fix footer search bar

---

src/pages/business-page/business-page.style.js

Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2208
Highlighted every name of unit.
|**![image](https://user-images.githubusercontent.com/34419998/201554983-4c0ca6b6-01fe-438e-a22e-daa9f63c4f81.png)**|**![image](https://user-images.githubusercontent.com/34419998/201555004-9b5c84c2-cfda-40b4-8a85-7143a1d78ca3.png)**|

Highlighted units name

---

src/pages/product-list-page/product-list-page.styles.js

Change color of pagination button when it's active.
| **![image](https://user-images.githubusercontent.com/34419998/201656762-c3626efc-60ec-466c-8ad4-d96a309c3217.png)** | **![image](https://user-images.githubusercontent.com/34419998/201656744-aef634d3-602d-49cc-b99b-0f6c106a12e2.png)** |

Fixed pagination button style

---

src/containers/social-links/social-links.styles.js

Fixed position of elements in footer:
- "HORONDI" title;
- social media icons.
|**![image](https://user-images.githubusercontent.com/34419998/201648129-2bb601bf-ad94-4283-be4d-97539e48bd6b.png)**|**![image](https://user-images.githubusercontent.com/34419998/201648157-2a2644df-0ad9-462a-a8e6-8159ae2c36c9.png)**|
|**![image](https://user-images.githubusercontent.com/34419998/201648218-57ef77ae-4b38-4aff-8388-c0a949915026.png)**|**![image](https://user-images.githubusercontent.com/34419998/201648249-f3ce0c86-15ba-4775-89c2-2878c6f35ffc.png)**|

Fixed style in footer 

---

src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
src/containers/orders/order-history/order-history-item/order-history-item.js
src/pages/wishlist/filled-wishlist/filled-wishlist.js

Should show order if size is removed

Changed price and size showing in orders

---

src/pages/product-details/product-details.js
src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap

fix back button

---

src/components/constructor-canvas/constructor-canvas.js
src/containers/checkout/checkout-form/delivery/worldwide/worldwide.js
src/containers/header-profile/header-profile.js
src/containers/language/language-component.js
src/containers/orders/cart/cart-item/cart-item.js
src/containers/search-bar/search-bar.js
src/containers/sidebar/sidebar.js
src/hooks/tests/use-currency.spec.js
src/hooks/use-cart.js
src/hooks/use-currency.js
src/pages/images-constructor/images-constructor.js
src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
src/pages/product-list-page/product-list-page.js
src/pages/product-list-page/product-sort/product-sort.js
src/pages/thanks-page/thanks-page.js
src/tests/unit/pages/product-list-page/product-list-page.spec.js

Fix console warnings and errors

---

src/components/number-input/number-input.js
src/containers/orders/cart/cart-item/cart-item.js

fix products quantity in cart

---

src/containers/language/language-component.js

The language should be underlined when Ukrainian is selected.
| ![Знімок екрана 2022-11-24 131528](https://user-images.githubusercontent.com/83120263/203828388-66d76cc9-0625-45e7-a924-7e72c99b745e.jpg) | ![Знімок екрана 2022-11-24 131449](https://user-images.githubusercontent.com/83120263/203828428-08bb4242-00cf-443c-85cc-c63517b6ba20.jpg) |

Deleted useRef

---

src/components/auth-form/auth-form-heading/auth-form-heading.styles.js
src/pages/recovery/recovery.js
src/pages/recovery/recovery.styles.js

Change styles in reset password page according to figma. And form is without different moving when appear an error.
| ![203142961-dc0e44c4-f945-4bd9-a650-7322f965bfa4 (1)](https://user-images.githubusercontent.com/83120263/203500769-ac68578d-5d0e-41b4-a9b0-477a5acad5b3.png) | ![Знімок екрана 2022-11-23 100703](https://user-images.githubusercontent.com/83120263/203500926-c3bf21d7-48bc-4fad-a82e-ab59989af5b1.jpg) |
| ![203142969-918c0e90-390a-4279-9f7a-d8764c30135c](https://user-images.githubusercontent.com/83120263/203500819-e6e4e4aa-3b0a-479c-be4a-6ca8bda67644.png) | ![Знімок екрана 2022-11-23 100612](https://user-images.githubusercontent.com/83120263/203500899-b27a5cae-e29c-4b …

Fixed styles in reset password page

---

src/components/number-input/number-input.styles.js
src/containers/orders/cart/cart-item/cart-item.js
src/containers/orders/cart/cart-item/cart-item.styles.js
src/containers/orders/cart/filled-cart/filled-cart.js
src/containers/orders/cart/filled-cart/filled-cart.styles.js
src/containers/orders/order/order-table/order-table.styles.js
src/locales/en/cart.json

Fixed horizontal scroll in the cart for mobile
| ![203510908-95261a79-7608-47cd-859c-8d5e62727b4b](https://user-images.githubusercontent.com/97129041/203976551-a63b11d4-2ca0-4d25-bc10-e34deb937e68.png) |![image](https://user-images.githubusercontent.com/97129041/203976517-28dd8d63-e39f-4c4f-b449-c152430ca8bd.png)|

Changed styles in cart for mobile

---

src/pages/images-constructor/operations/getConstructorByModel.queries.js
src/pages/images-constructor/use-constructor-loader.js

Found out the reason of incorrect pattern image
|  ![image](https://user-images.githubusercontent.com/45914032/204032604-f5fc6b02-db50-4a4d-af23-17c0aa0be07c.png)  |  ![image](https://user-images.githubusercontent.com/45914032/204032691-ee0f3dfb-834a-41c7-99c5-367d105c8c3c.png)  |

fixed bug with pattern image

---

src/pages/answers-questions-page/answers-questions-page.style.js
src/pages/business-page/business-page.style.js
src/pages/gift-certificate/gift-certificate.styles.js
src/pages/materials/materials.style.js
src/pages/news/news-page/news-page.style.js

Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2271
Fixed paddings of page title on some pages (on mobile version).
Pages: [Gift certificates], [Q&A], [Business pages], [News], [Materials]. 
Also, on [Materials] page fixed padding/margins between <div>.
|**![image](https://user-images.githubusercontent.com/34419998/204195170-4951e38b-b8fb-4197-8349-7b13e653d6c9.jpeg)**|**![image](https://user-images.githubusercontent.com/34419998/204195195-253e40ce-8d57-46c8-8402-25ca0758912f.jpeg)**|
|**![image](https://user-images.githubusercontent.com/34419998/204195788-40b25a28-01c3-4c23-8622-1b5b3e5e6638.jpeg)**|**![image](https://user-images.githubusercontent.com/344 …

Changed padding of page titles

---

src/containers/orders/order/your-order/order-item/order-item.js
src/containers/orders/order/your-order/your-order.js

Price of backpack from constructor in checkout page work corectly, even with another products.
| ![image](https://user-images.githubusercontent.com/83120263/204284546-41acd872-b985-49ad-9ea7-7ca11a1d66d8.png) | ![image](https://user-images.githubusercontent.com/83120263/204284597-5ad7c8ef-6dcb-4de5-ba16-bf1d59a5aac6.png) |

[Checkout page] Price of Backpack from constructor in checkout page is NaN

---

src/components/number-input/number-input.js
src/containers/checkout/checkout-form/checkout-form.js
src/containers/orders/cart/filled-cart/filled-cart.js
src/hooks/use-cart.js
src/pages/cart/cart.js
src/pages/gift-certificate/certificate-checkbox/certificate-checkbox.js
src/pages/profile-page/profile-page.js

Changed deleting products method, changed saving and showing phone numbers

[Checkout page] Price is lower if certificate was used in previous order

---

src/containers/orders/cart/filled-cart/filled-cart.styles.js

[Cart] Button 'go to checkout' change width when price change

---

src/configs/index.js
src/hooks/use-product-filters/use-product-filters.js

Fix console warning in use-product-filters hook

Bug/2163/fix console warning in use-product-filters hook

---

src/pages/profile-page/profile-page.js
src/utils/handle-profile-page.js

accaunt page doesn't crash and save button in profile page reacts on photo change

fix button and account page

---

src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
src/pages/product-list-page/product-list-filter/product-list-filter.js
src/pages/product-list-page/product-list-page.js

Now price filter removes from url when you set it by input fields.

now price filter removes from url when you set it by input field

---

src/pages/product-list-page/product-list-page.styles.js

Fixed current page color in catalog when you change to  dark theme.
|![image](https://user-images.githubusercontent.com/63456632/206196807-40409e1a-1403-47ea-ac78-3782dd8b617d.png)|![image](https://user-images.githubusercontent.com/63456632/206196914-3c8393fe-23f8-43d2-a135-dbf8a8ef3b2d.png)|

fixed current page color in dark theme

---

src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.styles.js
src/tests/unit/containers/search-bar-list-item/search-bar-list-item.spec.js

Fix search bar  on mobile adaptivity.
|![image](https://user-images.githubusercontent.com/56231198/206871019-d61d29e1-9a2e-4420-b0b3-df94195cdfd7.png)| ![image](https://user-images.githubusercontent.com/56231198/206871004-9f0a62b2-c95f-400b-9d97-8113805c0c89.png)|

fix adaptivity serach bar

---

src/containers/checkout/checkout-form/checkout-form.styles.js
src/containers/orders/order/your-order/order-item/order-item.js

Fix spaces between prducts at checkout page.
| ![image](https://user-images.githubusercontent.com/63456632/207289570-f7e537d4-d086-4bd6-b9f9-8ab67ecea548.png) | ![image](https://user-images.githubusercontent.com/63456632/207289659-bb2cbf54-8778-4a89-9d79-800112cdf4f2.png)
|

fix spaces between products

---

src/components/app/app-theme/app.typography.js
src/components/auth-form/auth-form-button/auth-form-button.styles.js
src/components/table/TableBodyRow/TableBodyRow.js
src/components/table/table.styles.js
src/containers/my-certificates/certificate-table/certificate-table.js
src/containers/my-certificates/certificate-table/certificate-table.styles.js
src/containers/my-certificates/filled-certificates/filled-certificates.js
src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
src/containers/my-certificates/notification-certificate-ends/notification-certificate-ends.styles.js
src/containers/orders/order-history/order-history-pagination/order-history-pagination.style.js
src/pages/order-history/constants.js
src/tests/unit/containers/my-certificates/certificate-table/certificate-table.spec.js
src/tests/unit/containers/my-certificates/filled-certificates/filled-certificates.spec.js
src/tests/unit/pages/my-certificates/my-certificates.spec.js

Added adaptivity to certificate page
|![image](https://user-images.githubusercontent.com/97129041/207358370-5010ca77-4f11-4aed-bb9a-fca07baab7a9.png) |![image](https://user-images.githubusercontent.com/97129041/207358581-3dc27c79-07cd-4f65-8ecd-dccaa9537f08.png)![image](https://user-images.githubusercontent.com/97129041/207358750-f2dec969-4475-4001-a209-fc12abfe610a.png)|

Fix "My certificate" page adaptivity

---

src/pages/home/our-looks/our-looks.style.js

Fixed images view on horondi style section.
| :----------------------: | :----------------------: |
| ![image](https://user-images.githubusercontent.com/63456632/207686385-0e1d29f8-eb06-4096-aa6f-11576cfa702d.png)|![image](https://user-images.githubusercontent.com/63456632/207686745-aa473405-2f3a-4bce-ace2-269aee64b883.png) |

fixed images adaptivity on horondi style section

---

src/pages/certificate-thanks-page/certificate-thanks-card/certificate-thanks-card.styles.js
src/pages/certificate-thanks-page/certificate-thanks-page.js
src/pages/certificate-thanks-page/certificate-thanks-page.styles.js

Changed styles in certificate thanks page.
|         Original          |
| ![image](https://user-images.githubusercontent.com/63456632/207115086-d7ee10e4-a25e-47b3-8c63-fcf32efd0306.png) |
|         Updated          |
|![image](https://user-images.githubusercontent.com/63456632/207115343-197fd4d0-4947-41c7-b195-7a9941f070d3.png)|

changed styles in certificate thanks page

---

src/components/scroll-bar/scroll-bar.js
src/components/scroll-bar/scroll-bar.styles.js
src/components/scroll-bar/tests/scroll-bar.spec.js
src/components/scroll-bar/tests/scroll-bar.variables.js

Changed scroll on click on home page
|![image](https://user-images.githubusercontent.com/97129041/207928275-6a23edf9-696c-47ac-9b28-cee962d82644.png)|![image](https://user-images.githubusercontent.com/97129041/207928353-9a6859b7-18e6-4094-b599-b26c6b99591b.png)|

Fixed content position, when using slider

---

src/components/page-title/page-title.js
src/components/page-title/page-title.styles.js
src/containers/header-right-bar/header-right-bar.styles.js
src/containers/orders/order/order-table/order-table.js
src/containers/products-filters-container/products-filters-container.styles.js
src/containers/search-bar/search-bar.styles.js
src/pages/product-list-page/count-per-page/count-per-page.styles.js
src/pages/product-list-page/product-list-filter/product-list-filter.styles.js
src/pages/product-list-page/product-list-item/product-list-item.js
src/pages/product-list-page/product-list-item/product-list-item.style.js
src/pages/product-list-page/product-list-page.js
src/pages/product-list-page/product-list-page.styles.js
src/pages/product-list-page/product-sort/product-sort.js
src/pages/product-list-page/product-sort/product-sort.styles.js
src/pages/product-list-page/tests/product-sort.spec.js
src/pages/wishlist/filled-wishlist/filled-wishlist.js

Fixed adaptivity in catalog
|![image](https://user-images.githubusercontent.com/97129041/208230482-ed72acb4-3ce6-4841-9485-0d509b2bb58c.png)|![image](https://user-images.githubusercontent.com/97129041/208230510-0049b4ec-0762-433f-81cf-5b73fad8f730.png)|

Fix adaptivity in catalog

---

src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
src/containers/checkout/checkout-form/delivery/worldwide/tests/worldwide.spec.js
src/containers/checkout/checkout-form/delivery/worldwide/worldwide.js
src/utils/handle-delivery.js

Autocomplete is valid in Nova Post, UkrPost, WorldWide.
Console is clear.
| ![image](https://user-images.githubusercontent.com/83120263/208231996-f3e99070-15b8-409b-9641-51e31d5ce2c7.png) | ![image](https://user-images.githubusercontent.com/83120263/208232001-d1456d8b-ebf4-4b70-b2f5-4a9648689b94.png) |

Added get option selected for autocomplete

---

src/pages/product-details/comments/comments.styles.js

remove border in cencel button when it is discebled

fix border in cancel button

---

src/containers/checkout/checkout-form/checkout-form.js
src/pages/thanks-page/thanks-page.js
src/redux/order/order.actions.js
src/redux/order/order.operations.js
src/redux/order/order.sagas.js
src/redux/order/order.types.js
src/redux/order/tests/order.actions.test.js
src/redux/order/tests/order.sagas.test.js
src/redux/order/tests/order.variables.js
src/tests/unit/pages/thanks-page/thanks-page.spec.js

Removed sending email from thanks page.

removed sending email from thanks page

---

src/components/app-footer/app-footer.styles.js
src/containers/orders/order/empty-order/empty-order.js
src/containers/orders/order/empty-order/empty-order.styles.js
src/containers/orders/order/order-table/order-table.styles.js
src/pages/product-details/comments/comments.styles.js
src/pages/product-details/constants.js
src/pages/product-details/product-description/product-description.styles.js
src/pages/product-details/product-details.js
src/pages/product-details/product-details.styles.js
src/pages/product-details/product-images/product-images.js
src/pages/product-details/product-images/product-images.styles.js
src/pages/product-details/product-info/product-info.js
src/pages/product-details/product-info/product-info.styles.js
src/pages/product-details/product-info/tests/product-info.test.js
src/pages/product-details/product-sizes/product-sizes.js
src/pages/product-details/product-sizes/product-sizes.styles.js
src/pages/product-details/product-submit/product-submit.styles.js
src/pages/product-details/similar-products/similar-products.styles.js
src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
src/pages/product-details/tests/product-details.spec.js
src/pages/product-details/tests/product-images.spec.js
src/pages/product-list-page/product-list-item/product-list-item.style.js
src/utils/productDetails.js

Changed styles in product, added adaptivity
|![Знімок екрана 2022-12-20 154304](https://user-images.githubusercontent.com/97129041/208687047-cfeae3c8-be0d-4d67-917b-443079264f10.png)![Знімок екрана 2022-12-20 154324](https://user-images.githubusercontent.com/97129041/208687054-3434427c-5c81-43be-9bd2-93121887a56a.png)![Знімок екрана 2022-12-20 154450](https://user-images.githubusercontent.com/97129041/208687057-e63648ab-85f3-4ab7-8143-3d5111dc065b.png)|![Знімок екрана 2022-12-20 154101](https://user-images.githubusercontent.com/97129041/208687145-e1106ee0-9d9b-4e13-ba57-b906ee48f6c5.png)![Знімок екрана 2022-12-20 154139](https://user-images.githubusercontent.com/97129041/208687 …

Changed styles in product, added adaptivity

---

src/containers/orders/cart/filled-cart/filled-cart.styles.js
src/pages/gift-certificate/gift-certificate.js
src/pages/gift-certificate/gift-certificate.styles.js

disable button when user don`t choose certificate

disable button when user don`t choose certificate

---

src/components/model-item/model-item.style.js
src/pages/home/categories-list/category-item/category-item.style.js

1. The names of models disappeared on hover.
Fixed it. Now the name of model is stable.
2. Changed text color of products while dark theme.
| **![image](https://user-images.githubusercontent.com/34419998/209232818-ade26898-b5a8-484b-b867-0c41216b82f2.png)** | **![image](https://user-images.githubusercontent.com/34419998/209233450-6c1df50a-097f-4a28-af34-9d1bb7bc1d0b.png)** |
|**![image](https://user-images.githubusercontent.com/34419998/209233227-8f196394-6db6-4796-ba19-9970abe1e010.png)**|**![image](https://user-images.githubusercontent.com/34419998/209233377-9de9674d-cd7a-436f-b67e-efad8e0cba3a.png)**|

Change style of some text on Home page

---

src/redux/user/tests/user.sagas.spec.js
src/redux/user/user.sagas.js

fixed loader in sagas

---

src/containers/orders/cart/filled-cart/filled-cart.js
src/containers/orders/cart/filled-cart/filled-cart.styles.js
src/locales/en/cart.json
src/locales/ua/cart.json

Changed discount displaying on 'filled cart' page and added some functionality for it.
|![image](https://user-images.githubusercontent.com/79856961/209724958-fb8900a2-2182-4d8d-b453-f460f4503474.png)|![image](https://user-images.githubusercontent.com/79856961/209725004-672426a5-d0e1-4554-966d-ccd6d5a9a7d8.png)|

Changed discount displaying on 'filled cart' page

---

src/containers/checkout/checkout-form/checkout-form.js
src/containers/checkout/checkout-form/delivery-type/delivery-type.js
src/containers/checkout/checkout-form/delivery/delivery.js
src/utils/checkout.js

Fixed values when change the delivery method within Ukraine.
| ![image](https://user-images.githubusercontent.com/83120263/209821152-af9e6751-2bdf-453c-bca1-c5cfec5bcf84.png) | ![image](https://user-images.githubusercontent.com/83120263/209821211-6530da66-0ec8-4294-b7e2-5fa2c6cc96c2.png) |

Values delete when change delivery type

---

src/components/back-button/back-button.js
src/components/back-button/back-button.styles.js
src/components/back-button/index.js
src/containers/checkout/checkout-form/checkout-form.js
src/containers/checkout/checkout-form/checkout-form.styles.js
src/containers/social-links/const.js
src/locales/en/footer.json
src/locales/ua/footer.json
src/pages/about-us/about-us.js
src/pages/answers-questions-page/answers-questions-page.js
src/pages/business-page/business-page.js
src/pages/business-page/business-page.style.js
src/tests/unit/containers/footer-lists/footer-lists.spec.js

add business page to footer
add back button to business page

add back button to business pages

---

src/containers/sidebar/sidebar-item/sidebar-item.js
src/pages/product-list-page/product-list-page.js
src/pages/register/register-from/register-form.js

fix code smells on client

---

src/pages/home/contructor-preview/constructor-preview.js
src/pages/home/contructor-preview/tests/constructor-preview.spec.js

removed unnecessary link to constructor page
