ita-social-projects/horondi_client_fe

src/pages/contacts/contacts.js, src/pages/contacts/contacts.styles.js
Now container for picture of contacts map will be hidden if image is not loaded.
=> Map is not displayed on the "Contacts"page #836

src/containers/chat/chat.style.js
Fixed responsive design for icons of 'Contact us' modal window. Made both icons same size and bring them in front of other elements.
=> Fixed responsive modal window 'Contact us'

src/pages/register/register-from/register-form.js, src/pages/register/register-from/register-form.styles.js, src/translations/user.translations.js
Fixed the label ‘by clicking Register, you agree to our Terms’ is not located below ‘Password’ input field in English language.
=> Fix label in Register form in English

src/validators/register.js
The error message 'Field should contain from 2 to 30 characters' appeared under 'Firstname' and 'Lastname' field when we typed >20 symbols. I fixed validation, now the error message appears if user enters >30 symbols. #759 
31 symbols:
=> Register page validation for firstname and lastname

src/pages/materials/materials.js, src/pages/materials/slider/slider.js, src/pages/materials/tests/materials.spec.js
Add functionality to detect broken imeges in patterns photos.
| ![image](https://user-images.githubusercontent.com/50678261/139476981-0161d26d-24c4-49aa-804c-8a984b2e8db6.png) | ![image](https://user-images.githubusercontent.com/50678261/139477132-339dbd50-4a70-4ccc-a046-4588c3b8b0c1.png) |
=> Pattern images preload in Materials

src/containers/checkout/checkout-form/checkout-form.js
Fixed translation order comment bug on the checkout page
| ** ![image](https://user-images.githubusercontent.com/57355852/141155167-b4b33287-1bc7-4c50-85c2-6e3375c29799.png) ** | **![image](https://user-images.githubusercontent.com/57355852/141154941-198b043b-fda4-4e36-bffe-843c97ddb831.png) ** |
=> fix checkout translation order comment (closes #1227)

src/containers/checkout/checkout-form/checkout-form.js
Fixed in checkout info validationSchema on Front, when we click on change language button the language of validationSchema error change. The language change correctly
| ![Screenshot from 2021-11-10 20-10-35](https://user-images.githubusercontent.com/89339465/141181102-84fe6072-4c0c-45de-8848-d9ec5eccea3f.png) | ![Screenshot from 2021-11-10 20-10-18](https://user-images.githubusercontent.com/89339465/141181172-0c6d0131-3056-4421-99cb-425865022f9e.png) |
=> Fixed error translations in checkout-info

src/containers/sidebar/sidebar.styles.js
Fixed social networks icons style colors when you switch on dark theme.
| ![Screenshot from 2021-11-12 20-19-44](https://user-images.githubusercontent.com/89339465/141517590-f9d5db54-6d95-4b74-a3b8-bf2a5f77ba54.png) ![Screenshot from 2021-11-12 21-11-35](https://user-images.githubusercontent.com/89339465/141522297-69cb731d-4ac4-4f90-acb9-7670ea847c23.png)| ![Screenshot from 2021-11-12 20-21-09](https://user-images.githubusercontent.com/89339465/141517655-ea6635c9-7056-4c07-a24c-82a1b11fadc3.png) ![Screenshot from 2021-11-12 21-10-55](https://user-images.githubusercontent.com/89339465/141522292-ae77a379-1b18-4ab0-bb47-458c6802e0ce.png)|
=> Fixed social networks icons style in dark theme 

src/containers/currency/currency.styles.js, src/containers/language/language.styles.js
Fixed white underline that appears with dark theme when you hover into the currency or language icon
Original:  
Updated
=> Fixed white underline that appears with dark theme

src/containers/cart-header/cart-header.styles.js, src/containers/header-right-bar/header-right-bar.styles.js, src/containers/wishlist-header/wishlist-header.styles.js
Fix bug with active zone of the wishlist and cart components from the header.
| ![before](https://user-images.githubusercontent.com/49168997/145809259-5298cea3-8c71-413d-a68d-3844be50fc83.jpg)|![after](https://user-images.githubusercontent.com/49168997/145809544-869984e3-1b21-469d-8c2b-cb5de246557a.PNG)![after_2](https://user-images.githubusercontent.com/49168997/145810012-49817f1a-9001-4e19-962f-d0bb3b29a170.PNG)|
=> Fix bug with wishlist and cart headers margin

src/components/modal/modal.styles.js, src/containers/checkout/checkout-form/checkout-form.styles.js, src/containers/currency/currency.styles.js, src/containers/language/language.styles.js, src/containers/orders/cart/cart-item/cart-item.styles.js, src/containers/orders/cart/filled-cart/filled-cart.styles.js, src/containers/orders/cart/path-back/path-back.styles.js, src/containers/orders/order/empty-order/empty-order.styles.js, src/containers/orders/order/order-table/order-table.styles.js, src/containers/search-bar/search-bar.styles.js, src/pages/home/categories-list/categories-list.style.js, src/pages/home/categories-list/category-item/category-item.style.js, src/pages/home/contructor-preview/constructor-preview.style.js, src/pages/home/slider/slider-home-page.style.js, src/pages/login/login.styles.js, src/pages/news/news-detail/news-detail.style.js, src/pages/news/news-item/news-item.style.js, src/pages/product-details/comments/comments.styles.js, src/pages/product-list-page/product-list-page.styles.js, src/pages/profile-page/profile-page.styles.js, src/pages/register/register-from/register-form.styles.js, src/pages/thanks-page/thanks-card/thanks-card.styles.js, src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js, src/pages/wishlist/wishlist-item/wishlist-item.styles.js
Make 'Open-Sans' main font family on frond and removed unnecessary font family css rules
=> (SP: 0.5) refactor/14518/make_open_sans_main_font_family

src/components/model-item/model-item.style.js, src/pages/home/models-list/models-list.style.js
First task was to fix models images cut on low height viewport. 
Also, Scrum master told me to make responsive view for mobile screen that should be 2 bags models in 1 row.
1) IMAGE CUT
origin: 
updated: 
2) MOBILE RESPONSIVENESS 
origin: 
updated:
=> fix models height and responivness for mobile

src/configs/routes.js, src/containers/sidebar/CertificateIcon.js, src/containers/sidebar/sidebar.js, src/containers/sidebar/sidebar.styles.js, src/locales/en/sidebar.json, src/locales/ua/sidebar.json, src/routes/routes.js, src/tests/unit/components/sidebar/sidebar.spec.js, src/tests/unit/pages/order-history/order-history.spec.js
In the burger menu, after the “accessories” tab add a link to “Buy gift certificate” that redirects us to a Page where we can buy a Certificate
| ** ![до](https://user-images.githubusercontent.com/59199055/147966343-e143de15-5c3b-443d-9217-fa00212736cf.jpg) ** | ** ![image](https://user-images.githubusercontent.com/59199055/148273465-3425dd05-57c9-4492-afaf-ec497d00373b.png) ** |
=> link to By gift certificate and route to the page was created

src/pages/home/categories-list/category-item/category-item.js
useEffect will try to keep communications with our fetch-data procedure even while the component has unmounted. Since this is an anti-pattern and exposes our application to memory leakage, cancelling the subscription to useEffect optimizes our app.
| ** 
** | ** updated screenshot ** |
=> Fix console error in CategoryItem

src/containers/orders/order-history/order-history-item/order-history-item.js
The issue is "two children have the same key".  I changed the logic of generation the unique key in map method for "OrderHistoryItem"
| ** ![зображення](https://user-images.githubusercontent.com/65071268/149394136-1b197cff-958c-4b18-a747-ae3db6d6e5c7.png) ** | ** updated screenshot ** |
=> fix console error OrderHistory

src/containers/chat/chat.style.js, src/index.css
Changed styles for messages icons to fit them with facebook icon. Also facebook dialog window position was changed by using ```!important``` tag. It was necessary because iframe has his own styles.
| ** ![image](https://user-images.githubusercontent.com/39667486/147524921-4d8c1f86-88c6-48c4-a624-4420b316f40d.png) ** | ** ![image](https://user-images.githubusercontent.com/39667486/147525142-a47e5b6b-a3a0-4ce0-a959-c1ed1290d45c.png) ** |
=> Align messengers icons and fixed facebook dialog position

src/locales/en/error.json, src/pages/register/register-from/register-form.styles.js, src/validators/register.js
'Email' field can contain less than 8 and more than 60 characters. Error message below 'Email' field does not appear
| ** 
** | **
** |
=> email fail message was added

src/pages/product-details/comments/comments.js
Fix tooltip position on comments form buttons, when user unregistered 
| ![image](https://user-images.githubusercontent.com/79531224/150204797-55706dcc-d3f9-418e-a0d8-ae18b335ebd9.png) | ![image](https://user-images.githubusercontent.com/79531224/150204843-614d4a7c-f75f-4eb3-8940-996c853cf8ed.png)|
=> fix tooltip position on comment form buttons

src/validators/checkout.js
after entering extra symbols into 'Email' field on Checkout Process the page crashes
| ** ![до](https://user-images.githubusercontent.com/59199055/150468960-3f0c4f96-b7e1-4621-856d-75edb32dd2cf.png) ** | ** ![після](https://user-images.githubusercontent.com/59199055/150468975-9fa6ed63-48c8-4ff6-9bfd-3a9272c66a57.png) ** |
=> error fild to email was added

src/pages/wishlist/empty-wishlist/empty-wishlist.js
fix button styles on EmptyWishList page according to new design
|![image](https://user-images.githubusercontent.com/64384450/150388069-7846dfef-3f42-42ae-802f-5dc6ca89c8c0.png)| ![image](https://user-images.githubusercontent.com/64384450/150388187-b5484fbf-749c-4832-a59d-57754062dfc6.png) |
=> fixButtonStyles

src/locales/en/cart.json
When the cart is empty, the "TO CATALOG" button is not translated into English. (Fixed)
=> fix translations button to catalog in the cart

src/utils/client.js
Now access token gets removed from local storage when expired.
=> Fixed wishlist error

src/containers/sidebar/sidebar.styles.js
fixed empty space in burger when page is scrolled down
|![image](https://user-images.githubusercontent.com/61072426/153190955-6e35a074-1596-4d67-a62f-aba0da334337.png)|![image](https://user-images.githubusercontent.com/61072426/153191049-535707e9-1ff9-4597-b9ed-63fb600547a5.png)|
=> hotfix-of-bugfix/1591/burgerMenuHeight

src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
Price filters no more allows to put negative numbers.
=> Bugfix/1089/not allow negative numbers in price filter 

src/components/model-item/model-item.js, src/components/model-item/model-item.style.js, src/pages/home/models-list/models-list.style.js
Changed sizes of flex-container that allowed incorrect view of products cards.
Also noticed the incorrect view of block header.
**Original**         
**Updated**
=> Fixed view of products

src/containers/sidemenu-right-bar/sidemenu-right-bar.styles.js
Changed styles property in order to make wishlist and cart icons not to overlap facebook and instagram icons
| ![image](https://user-images.githubusercontent.com/84774115/161912021-368c46cf-852c-4516-9d88-6a391108f9fb.png) | ![image](https://user-images.githubusercontent.com/84774115/161911930-1381b562-7b8a-436b-936d-484e08435763.png) |
=> fixed bug with overlaping icons

src/containers/chat/chat.style.js
Added scroll for Chat, and move Chat down becouse the upper part of the Chat window was under the header
| ![before](https://user-images.githubusercontent.com/100776036/162612256-b3edf748-29f3-4dde-a5be-5ad256fc5525.png) | ![after](https://user-images.githubusercontent.com/100776036/162612259-9c32e74c-0994-4fb2-ab4d-146d66a4b8c1.gif) |
=> [Customer Support Chat] Button 'Send' goes outside Customer Support Chat window 

src/components/constructor-canvas/constructor-canvas.js, src/containers/orders/operations/getConstructorByModel.query.js, src/containers/orders/order-history/order-history-item-product/order-history-item-product.js, src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js, src/containers/orders/order/your-order/order-item/order-item.js, src/pages/order-history/operations/order-history.queries.js, src/tests/unit/components/order-history-item/order-history-item.spec.js, src/tests/unit/components/order-history-item/order-history-item.variables.js, src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js, src/tests/unit/components/order-history-list-item/order-history-item-product.variables.js
I have added canvas image to order-item and order-hustory.
|         Original          |
| ![](https://clip2net.com/clip/m0/a7404-clip-43kb.png?nocache=1) |
|         Updated          |
|  ![](https://clip2net.com/clip/m0/2f296-clip-21kb.png?nocache=1)  |
=> Add canvas image to orderItem from constructor on order-history and checkout pages

package.json, src/containers/chat/chat.js, src/containers/chat/chat.style.js, src/containers/chat/tests/chat.spec.js, src/index.css
1. Added 'react-messenger-chat-plugin' to dependencies instead of 'react-messenger-customer-chat', which allows you to hide and show the messenger instead of reloading it every time.
2.  Changed header text on the Facebook Messenger page from 'Horondi' to 'Horondi Consultant'.
| ![facebookMesseger3](https://user-images.githubusercontent.com/59802802/165326454-912af0c7-6f56-4770-8c47-ebbcef2b4ec3.gif) | ![facebookMesseger2](https://user-images.githubusercontent.com/59802802/165322627-2f3f3eb4-224f-4a6b-8ac9-2b2f3621eaa3.gif) |
=> Fixed facebook messenger bugs

src/containers/language/language-component.js
When visiting a page, according to selected button, the language was Ukrainian, but it was in English. Now it is Ukrainian as it has to be
| ![Screenshot 2022-05-19 at 09-41-39  Home Page, Subpages  Home Page, Subpages aren't displayed in Ukrainian by default when v](https://user-images.githubusercontent.com/49586997/169227159-039cd46f-a8e2-4771-9c2e-255119a659c9.png) | ![Screenshot 2022-05-19 at 09-42-25 Horondi](https://user-images.githubusercontent.com/49586997/169227268-cf39b582-75a7-4c89-a848-ed733f379e31.png) |
=> ukrainian language on load

src/validators/register.js
Fixed regisatration page validation schema.
| ** original screenshot ** | ![image](https://user-images.githubusercontent.com/80908916/170081323-ce1ff0de-03f6-40b3-97a2-cd5dbc813510.png) |
=> Bug fix/1935/regisatration page/user can register with an invalid email

src/containers/sidebar/sidebar.styles.js
Burger menu now looks fine on 320px devices
| ![Screenshot 2022-06-02 at 13-32-13  SP 0 5   Burger menu  - Goes beyond the screen at smaller screen size · Issue #1961 · it](https://user-images.githubusercontent.com/49586997/171611380-5cc4a82c-f859-4346-8df1-81b88e4df8db.png) | ![Screenshot 2022-06-02 at 13-33-22 Horondi](https://user-images.githubusercontent.com/49586997/171611426-f62f7e2c-9c13-4d99-8979-93e9c75b2835.png) |
=> fix drawer sidebar at smaller screen sizes

src/pages/wishlist/wishlist-item/wishlist-item.styles.js
Now wishlist items look correct
| ![Screenshot 2022-06-02 at 13-37-15  SP 0 5   Wishlist  - Item columns are placed too close at smaller device size · Issue #1](https://user-images.githubusercontent.com/49586997/171612116-a66e2a57-1f1b-43f6-ba37-a2a674744aa1.png) | ![Screenshot 2022-06-02 at 13-37-56 Horondi](https://user-images.githubusercontent.com/49586997/171612167-8151eddb-294a-4057-952c-2d6434bdfceb.png) |
=> fix wishlist column margin

src/containers/chat/chat.js, src/containers/chat/chat.style.js
Now facebook message icon is not overlapping over search results
| ![Screenshot 2022-06-08 at 13-34-33  Home Page Search  Messenger icon is displayed over search results · Issue #1991 · ita-so](https://user-images.githubusercontent.com/49586997/172596077-227dc18b-0a96-4a28-a0dd-c45372d9b5f5.png) | ![image_2022-06-08_13-25-58](https://user-images.githubusercontent.com/49586997/172596229-e0f33bd7-2796-4df2-ab73-17b7a2612325.png) |
=> facebook icon z-index

src/containers/chat/chat.js, src/pages/product-details/product-info/product-info.js, src/pages/product-details/product-info/product-info.styles.js, src/pages/product-details/product-sizes/product-sizes.styles.js
Now, in product details, by clicking on pattern, user can see zoomed image of that pattern
|  | https://user-images.githubusercontent.com/49586997/173808795-d9d74efe-6c8f-4b5d-b174-7fcabee201ba.mp4 |
=> preview pattern in product detail

src/pages/materials/slider/slider.styles.js
On materials page, materials photo were disappearing when user hover them. The error was only on firefox
| ![image](https://user-images.githubusercontent.com/84774115/174662465-e06d560b-0fb9-4c02-ac22-270ebe881459.png) | ![image](https://user-images.githubusercontent.com/84774115/174662481-7704ba85-7e79-458c-99a3-343bdb606ecd.png)|
=> materials photo disappear bug fixed

src/components/app-footer/app-footer.js, src/components/app-header/app-header.js, src/components/app-header/app-header.styles.js, src/containers/chat/chat.style.js, src/containers/checkout/checkout-form/tests/checkout-form.spec.js, src/containers/checkout/checkout-form/tests/checkout-form.variables.js, src/containers/orders/cart/cart-item/tests/cart-item.variables.js, src/containers/orders/operations/order.queries.js, src/routes/routes.js
- Fixed width change when Material UI sets overflow to hidden.
- Fixed product thumbnails.
=> Fix width change when scrolling is locked

src/routes/routes.style.js
now there is no empty space between footer and content
=> fixed gap between content and footer

src/containers/orders/order-history/order-history-item-product/order-history-item-product.js, src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js, src/containers/orders/order-history/order-history-item/order-history-item.js, src/containers/orders/order-history/order-history-item/order-history-item.styles.js, src/containers/orders/order-history/order-history-table/order-history-table.js, src/containers/orders/order-history/order-history-table/order-history-table.style.js, src/hooks/use-currency.js, src/pages/order-history/operations/order-history.queries.js, src/pages/order-history/order-history.styles.js, src/tests/unit/components/order-history-item/order-history-item.spec.js, src/tests/unit/components/order-history-item/order-history-item.variables.js, src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js, src/tests/unit/pages/order-history/order-history.variables.js
Fixed order history prices now are shown with discount, fixed styles
| ![order_history_old](https://user-images.githubusercontent.com/97129041/194388895-6c29fede-f26f-43a4-b721-552823c3dac3.png) | ![order_history_new](https://user-images.githubusercontent.com/97129041/194388866-4cbef970-a952-4a9d-b400-3c8886259b08.png) |
=> Orders history prices without discount

src/pages/product-details/product-images/product-images.styles.js
Fixed text colour at product page
Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2160
| **![image](https://user-images.githubusercontent.com/34419998/197903719-679ef3c6-8c4e-4f0d-bc9b-ce473c825ca2.png) ** | ** ![image](https://user-images.githubusercontent.com/34419998/197903858-acc41793-81e0-4282-8e3c-de28af15d27a.png)** |
=> Change colour of lastImageText on product page

src/containers/social-links/social-links.styles.js
Fixed styles in footer (in order to decrease space between titles when screen size is changed).
Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2155
|**![image](https://user-images.githubusercontent.com/34419998/199041198-9d51b9ab-f875-451d-9487-5ec51a85b35b.png)**|**![image](https://user-images.githubusercontent.com/34419998/199041278-5ae178e2-7517-424e-bcc0-4b7c75b0f556.png)**|
=> Fixed styles in footer

src/pages/home/categories-list/categories-list.style.js, src/pages/home/models-list/models-list.style.js
Fixed space in section 'catalog'.
Also fixed space in section 'models'.
Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2144
|**![image](https://user-images.githubusercontent.com/34419998/199102470-d92fc58a-bec5-4e93-9517-606f9bdc49eb.png)**|**![image](https://user-images.githubusercontent.com/34419998/199102538-4969ce5b-2164-435c-a4c6-48e32c6e62c2.png)**|
|**![image](https://user-images.githubusercontent.com/34419998/199102699-6f802460-0c49-4451-900c-db43cc777877.png)**|**![image](https://user-images.githubusercontent.com/34419998/199102740-37190836-0d27-4119-9b94-050394c4a945.png)**|
=> Fixed spaces between sections

src/containers/header-profile/header-profile.styles.js
Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2211
dropdown list changes size when you change the language.
Result:
fixed width of this dropdown list.
|**![image](https://user-images.githubusercontent.com/34419998/200411678-c8d9a789-6ede-44f5-aeff-41becae3d8fd.png)**|**![image](https://user-images.githubusercontent.com/34419998/200411703-063e8649-358b-480a-87d2-9cfa9031877b.png)**|
=> change width

src/pages/gift-certificate/gift-certificate.js, src/pages/gift-certificate/gift-certificate.styles.js
Changed border color of text field. Must be red when we input text while error message.
Bug: https://github.com/ita-social-projects/horondi_client_fe/issues/2114
|**![image](https://user-images.githubusercontent.com/34419998/201230200-1833754b-fb8d-4323-8c21-d61cc531011e.png)**|**![image](https://user-images.githubusercontent.com/34419998/201230175-6e73c618-84e0-4a4d-a29f-c9bfdb729588.png)**|
=> Changed border color of text field

src/pages/product-details/product-path/product-path.js
When selecting a category, it redirects to the catalog without the selected category and shows all products
Before 
After
=> redirect to choosen category

src/containers/checkout/checkout-form/checkout-form.js, src/containers/checkout/checkout-form/checkout-form.styles.js
Your order block stop scrolling with page when width is less than 1150px. -> Fixed!
On mobile your order shoul be located in the center. -> Fixed!
Deleted some useless css properties.
| ![image](https://user-images.githubusercontent.com/94409173/201094377-abbeeac7-70ea-4a2d-abd5-fd007eb42ac0.png) | ![image](https://user-images.githubusercontent.com/94409173/201094460-0266df67-b781-4c6c-ad88-fca7933b1695.png) |
=> [Checkout] Fix styles for your Order in checkout page

src/pages/product-details/product-sizes/product-sizes.styles.js
In the dark theme, the button has a different color
| ![image](https://user-images.githubusercontent.com/83120263/204088873-82b7f3e8-697a-40d6-9aa4-2726169abc37.png) | ![image](https://user-images.githubusercontent.com/83120263/204088862-7be68582-aa62-49dd-b90a-db5ecaadc8c2.png) |
=> Changed styles for button size in dark thema

src/pages/product-details/comments/comments-item/comments-item.js, src/pages/product-details/comments/comments-item/comments-item.styles.js
Now tooltip for feedback icon at comments works correctly.
|         Updated          |
| ![image](https://user-images.githubusercontent.com/63456632/204267100-83d0454b-673b-442d-bda7-122113a2a95c.png)|
=> now tooltip for feedback icon works correctly

src/pages/news/news-item/news-item.style.js
Fixed distance between blocks (on mobile version).
Also, fixed position of blocks with news (when screen width was between 767px and 753px).
| **![image](https://user-images.githubusercontent.com/34419998/204687521-38b08e1a-80e3-47a5-8e17-01a650e9341b.png)** | **![image](https://user-images.githubusercontent.com/34419998/204687553-b2b19771-3e16-4411-b01c-5bb9a0ee7d0f.png)** |
|**![image](https://user-images.githubusercontent.com/34419998/204687615-0f3e01c4-3d58-4a79-868a-b20ae6694935.png)**|**![image](https://user-images.githubusercontent.com/34419998/204687641-ddc5a374-274a-4356-8813-f66a41b0c7b2.png)**|
=> Changed position and distance between news blocks

src/containers/orders/order-history/order-history-item-product/order-history-item-product.js, src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
Fixed items size in order history (mobile adaptivity)
| ![image](https://user-images.githubusercontent.com/83120263/208118437-2e6cbece-34bd-4ac3-8b93-0453ab93c992.png) | ![image](https://user-images.githubusercontent.com/83120263/208118458-791886c6-7fff-4d3b-a14f-f19fb865dfa9.png) |
=> Changed styles for order history

src/pages/news/news-item/news-item.style.js, src/pages/news/news-page/news-page.js, src/pages/news/news-page/news-page.style.js, src/pages/order-history/order-history.styles.js
Should have gap in news section between pagination and footer.
Pagination hide when quantity page  equal 1.
| ![image](https://user-images.githubusercontent.com/83120263/208254776-62cd59c7-6e87-4242-a201-6f5d7e80d7fe.png) | ![image](https://user-images.githubusercontent.com/83120263/208254866-b1b13ac1-856b-4978-bdcf-c1dea458bc38.png) |
=> Should have gap in news section between pagination and footer

src/containers/orders/order-history/order-history-pagination/order-history-pagination.style.js, src/pages/product-list-page/product-list-page.styles.js
The selected pagination element has a correct border on the catalog page and order history.
| ![image](https://user-images.githubusercontent.com/83120263/208853551-17b41d5b-099b-418d-826f-32845a034239.png) | ![image](https://user-images.githubusercontent.com/83120263/208853788-ac34ea09-889b-4e99-8669-aef3212e8578.png) |
=> The selected pagination element has a correct border on the catalog page and order history.
